### ISSUE TITLE
Provide a way from reaction to core.async chan

### ISSUE THREAD

**Issue by skrat** [Day8/re-frame#105]
I don't think it's that uncommon that you actually need to turn a reaction (or better yet, subscription handler), into a `core.async` `chan` of updates. Now with the common toolkit one would think he can just use `add-watch` on the `Reaction` returned by `subscribe` but that apparently doesn't work. Neither does this snippet:
```
(defn subscribe-chan [s]
  (let [ch (chan)
        re (subscribe s)
        ar (make-reaction (.-f re) :auto-run true :derefed [])]
    (add-watch ar :render (fn [k r o n] (put! ch n)))
    ch))
```
And of course what's being put onto the chan should be up to user (diff?). Any ideas?

**Comment by danielcompton** [comment]
I don't have a computer handy to test this, but there's a few questions that stick out to me here. 

* Should re just be derefed in make-reaction?
* Do you need a buffer on the channel?
* instead of creating a reaction and watching it, why not put the values on the chan in the reaction directly?

    (run! (put! ch @re))

This feels like it's creeping away from re-frame's FRP into something else. I haven't yet run into a situation where I've wanted a channel to convey changes in a reaction. Sticking with the data flow re-frame provides works is generally a good idea. However I'm sure there are some valid use cases. What are you wanting to use it for?

**Comment by skrat** [comment]
Basically I have an app with WebGL renderer and some GUI. For the GUI part, I use re-frame and am pretty happy about it. But the renderer is using "input streams", like the FPS timer ticking, mouse, keyboard, model data, etc. I modeled this with core.async channels and transducers and it works surprisingly well. I'm trying to get data from GUI, when changed, and pipe it to the renderer. In the renderer, I merge all the input channels into one, then I have a single pure reducing function over renderer state, that takes the current state, the even being processed, and returns a new renderer state. This renderer state is then passed to the `draw` functions.

I could re-do the renderer with Reactions instead of core.async chans, but how? The idea of having a chan out of a subscription is very attractive because of the both the simplicity and ease of implementation.

**Comment by mike-thompson-day8** [comment]
@skrat the approach suggested by Daniel will work .. for some definition of "work" ... 

But there's one serious problem ... 
```clj
(defn subscribe-chan [s]
  (let [ch     (chan)
        signal (subscribe s)
        r      (run! (put! ch @signal))]    ;;  <--- what will ever call (dispose)  on r  ??
    ch))
```

There is no way that `dispose` will ever be called on `r`.  So this mini-signal graph (finishing in `r`) won't ever get cleaned up.  I can't imagine that's good ?? Maybe, you could link the closing of the channel `ch` with a `(dispose r)`, maybe. 

But, honestly, I feel like I'm looking at Frankenstein on the slab.  I'm worried about the eyes flicking open.  

Is there any reason that your "render-state" can't be stored in `app-db` ?  That  is where state should be stored in a re-frame app.  That state should be calculated in event handlers.  And it should be "served" by subscriptions to your `draw` functions.

**Comment by skrat** [comment]
@mike-thompson-day8 Yes @danielcompton solution indeed works, I misunderstood what `run!` is for. Disposing `r` upon channel close sounds good to me, whatever the type of `r` is (?).

The reason render-state is not stored in re-frame's managed `app-db` is that while re-frame reagent do have mechanics to re-render the DOM, there's nothing helping me to re-render my scene-graph (render-state) into WebGL context.

There are two ways:

A) re-render WebGL in fixed intervals using render-state from re-frame's managed app-db.
B) re-render WebGL when something has changed

Option A would play nice with de-referencing subscriptions in the `draw` function, but not with option B. Additionally, changes to render-state have to be reflected in a side-effecful way, because in WebGL, or anywhere where you want to utilize GPU, you have to manage resources on it yourself. Therefore I need a place in my app where I can synchronize the resourced allocated on the GPU, whenever the render-state changes. Any ideas?

**Comment by hkjels** [comment]
I'm looking into doing some svg-animations with [bardo](/pleasetrythisathome/bardo) for transitions. Bardo uses core.async internally, so I might need a similar solution. Am I strongly advised not to? And if so, what's really the option?
Btw, I'm new to clojure, re-frame etc.

**Comment by danielcompton** [comment]
I think this can be closed for now? Feel free to continue this discussion on the Reagent mailing list, but I don't think there is a specific feature or bug being discussed here?
