### ISSUE TITLE
PhoneCat As An Example?

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#11]
Should we consider converting this to a re-frame example:
https://github.com/vvvvalvalval/reagent-phonecat

**Comment by gadfly361** [comment]
:+1:

**Comment by dhruvp** [comment]
Hey @mike-thompson-day8 . I've taken a stab at steps 1-4. Will have 5 on done shortly. The repo is here: https://github.com/dhruvp/angular-phonecat-re-frame. Let me know what you guys think.

**Comment by mike-thompson-day8** [comment]
@dhruvp This is excellent thanks!!

I'm currently in the develop branch finishing up an alpha of v0.2.0 (which has a couple of minor breaking changes). I'm refusing to let myself get distracted on anything until I push.  But I'll have a look at your stuff the moment I'm finished.  

Thanks again!

**Comment by dhruvp** [comment]
Hey that sounds good @mike-thompson-day8 . I'm really excited about the architecture you're putting together and am happy to help!

**Comment by dhruvp** [comment]
Hey @mike-thompson-day8 I've finished everything till step 10. You can see it here: https://github.com/dhruvp/angular-phonecat-re-frame . I have one bug that I can't quite fix. It looks like the app-db atom passed into handlers doesn't quite behave correctly when I try and route to a different page. Not sure if that's an issue with my code or potentially a bug in re-frame. Regardless if you hit every page and refresh it everything works. Let me know when you get a chance to take a look!

Thanks,

Dhruv

**Comment by mike-thompson-day8** [comment]
@dhruvp  this is absolutely terrific, thanks!!  I'm sticking my head up now I have v0.2.0 out the door. I'll have a browse over the code and be back to you shortly.

**Comment by dhruvp** [comment]
Hey @mike-thompson-day8 I'm also working on an explanation that goes along with it. Here's the first draft: http://dhruvp.github.io/2015/03/07/re-frame/. Only finished up to step 4. Again I'm sure there are improvements so I'd love to hear your thoughts.

Thanks!

Dhruv

**Comment by mike-thompson-day8** [comment]
@dhruvp   It looks like your blog post has already been picked up by Plant Clojure
https://twitter.com/planetclojure/status/574831512211755009

Which might be faster than you'd wanted.

**Comment by mike-thompson-day8** [comment]
@dhruvp Would it be best for me to review step 10, and give feedback on it.  That would then flow down to the other, earlier steps?  Or another approach?

**Comment by dhruvp** [comment]
Hey Mike!

That sounds perfect. I can apply your feedback from step 10 and clean
everything else up. Also I have no idea how planet Clojure found the post
haha. It's definitely not ready yet so I'll probably take it down
temporarily.

Thanks!

**Comment by dhruvp** [comment]
Hey @mike-thompson-day8 !

I fixed the dependency on 0.1.7. I'm also going to move all the instructions from the blog into the readme of the repo itself. I think that makes more sense.

**Comment by dhruvp** [comment]
Also moved the explanation stuff straight to the [repo](https://github.com/dhruvp/angular-phonecat-re-frame). All steps are now explained. I need to edit the explanations but will do that when I get some more time.

**Comment by mike-thompson-day8** [comment]
@dhruvp  I'm reading through ... will note things in code as I go.  

I was scanning the code in the readme and noticed that you need to change   `(assoc db [:a] 3)`   ->   `(swap! db assoc [:a] 3)`

**Comment by mike-thompson-day8** [comment]
I can't comment in the code, so I'll comment here ..  

Looking at components like `thumbnails` and `phone-info-template` I can see you using maps as `:keys`.   You really need to be supplying numerical or string ids.

**Comment by dhruvp** [comment]
Hey thanks again for taking a look. I've fixed everything you mentioned. Just out of curiosity, why don't use maps as the keys and instead prefer strings or numbers?

**Comment by dhruvp** [comment]
Also to make it easier to make comments, I've added this PR here: https://github.com/dhruvp/angular-phonecat-re-frame/pull/1/files

**Comment by dhruvp** [comment]
Hey @mike-thompson-day8 any updates on this? Thanks again!

**Comment by mike-thompson-day8** [comment]
No updates. Was there any area that you felt needed further review?  I'm a bit focused on pushing out v0.3.0  (even nicer subscriptions!!)  I've lost track of what further I should do on this, sorry.

**Comment by dhruvp** [comment]
Ok awesome. Wasn't sure if you had any further feedback and were waiting on me to fix things. And great to hear there are new subscriptions!  Re. the phonecat work, would it be worth adding, along with the todo mvc examples etc. to an example section in the Readme? Totally up to you, not trying to push how you display your readme.

**Comment by mike-thompson-day8** [comment]
@dhruvp thanks for your work on this!
