### ISSUE TITLE
FAQ Entry suggestion: wire up re-com model atoms with your re-frame handlers

### ISSUE THREAD

**Issue by Martin-S-Weber** [day8/re-frame#112]
Handler-induced App DB state changes don't update my re-com atom models, help!

**Question**

Problem: You're using the excellent re-com widgets and have opted for having an interactive component (such as a slider) and wisely chose to have its state backed by an atom. You are wondering how to update said atom from your handlers. So you ask yourself: how to do it?

**Answer**

Keep calm and try to take over the world one line of clojurescript at a time.

Example: Think about a media player using md-icon-buttons. There's a slider when a song is playing. If you hit fast forward, or skip to beginning, you want the slider to update. You chose an atom as the slider model so that playback code etc. doesn't need to worry about the view, as long as the atom is updated.

``` clojure
;; First, reflect and notice your view wants to tell re-frame that it needs help.
;; Secondly, you wisely grouped your view-related control messages in a way so that they 
;; wrap easily (i.e., can be serviced by a single handler).
(re-frame/register-handler
  :player-controls
  (fn player-controls-handler [db [_ control & args ]]
   ; Then, combine these things:
   ; (1) handle sync requests
   ; (e) establish db-comparer to update synced models
   ; (pi) use it
   ; we begin with (e) :
    (let [; state setup for watching paths in db to signal updates to atoms functionality
          now-values (into {} (map (fn path-to-value [[path models]] [path (get-in db path)]) (get-in db [:plr :synced]))) ; get current values
          signaling (fn [new-db]                                              ; fn to perform signaling to atoms if necessary
                      (doseq [[path models] (get-in new-db [:plr :synced])]   ; foreach [path => [model, model, ...]] to
                        (let [new-value (get-in new-db path)]                 ; get new value
                          (when (not= new-value (get-in now-values path))     ; compare to old, if different
                            (doseq [model models]                             ; walk through models to ..
                              (reset! model new-value)))))                    ; set them to the new value
                      new-db)                                                 ; return new db so we can wrap our handlers below
          ]

 (condp = control ; dispatch :player-control events
        ; (1) handle sync storage
        ; just stuff it into the App DB. We don't need other state storage.
        :needs-sync (let [[model path] args
                          current-syncs (get-in db [:plr :synced])
                          subscribed (if (get-in current-syncs [path]) 
                                       (update-in current-syncs [path] conj model)
                                       (assoc-in current-syncs [path] [model]))
                          ]
                      (assoc-in db [:plr :synced] subscribed))
        ; handle real player controls
        ; use (pi) the db compare and model updater (signaling)
        :skip-previous (signaling (db-adjusting-impl skip-prev-computation))
        :replay-30 (signaling (db-adjusting-impl replay-30-computation))
        :replay-10 (signaling (db-adjusting-impl replay-10-computation))
        :replay-5 (signaling (db-adjusting-impl replay-5-computation))
        :fast-rewind (signaling (db-adjusting-impl fast-rewind-computation))
        :fast-forward (signaling (db-adjusting-impl fast-forward-computation))
        :forward-5 (signaling (db-adjusting-impl forward-5-computation))
        :forward-10 (signaling (db-adjusting-impl forward-10-computation))
        :forward-30 (signaling (db-adjusting-impl forward-30-computation))
        :skip-next (signaling (db-adjusting-impl skip-next-computation))))))
```

In the view you'd then use

``` clojure
(re-frame/dispatch-sync [:player-controls :needs-sync model-atom [:path :into :db]])
```

(`sync` so the atom gets initialized with the value from the DB right away)

Your "model" (i.e. the implementing handler) would store the real naked value for the use inside the `model-atom` (i.e., for use by the view / re-com widget) inside the app-db under the path the view component expects to find it (`[:path :into :db]`)

(in `db-adjusting-impl`, for example)

``` clojure
(defn db-adjusting-impl [db callback]
  (update-in db [:path :into :db] callback))
```

**Comment by Martin-S-Weber** [comment]
Note that this could probably be wrapped in a middleware for event handlers that looks for a 2nd key ```:needs-sync``` in there; does the ```(signaling)``` setup as above and then benefit? Anyways, what do you think of the solution, does it fit well into the re-frame way of thinking (feels a bit cheaty I admit, but I've used a subscription for a re-com slider data model before and it's no fun)?

**Comment by Martin-S-Weber** [comment]
Now I'm aware of the mantra, don't wire in state, but let react redraw your UI upon user interaction and make it _look like_ it's actually updating state destructively..  But this is motivated from using an interactive component which controls data being displayed and, naturally, its own display, the latter of which you preferrably want to redraw "one cycle earlier" than the DOM of the view the component generates. Say you have a slider that controls selection of one of .. 20k values. When you're rushing through the length of the slider, you want it to update with higher frequency than the view. This is sorta achieved already by creating the view by dispatching (not -sync) with re-frame and having it defer the generation of the view until the next cycle. 

I had the impression that by backing such a slider with a reagent/atom instead of using the value from a subscription, the updates were running more smoothly with violent entry value changes, which is why I came up with the crutch above.

**Comment by dijonkitchen** [comment]
Any updates or should it be closed?

**Comment by superstructor** [comment]
I've read this issue a couple of times now and I don't really understand what is required. @danielcompton marked it with a "docs" tag at one point, so perhaps he understood and thought better docs was all that was needed?

I’m currently spring cleaning issues, and this one appears to be very old, and has atrophied without a clear path forward, including what better docs might be necessary,  so I'm going to close it.
