### ISSUE TITLE
Add a visualisation of the hierarchy of subscriptions

### ISSUE THREAD

**Issue by yatesco** [Day8/re-frame#117]
More and more I am treating the UI as a normalised database with queries and build on queries that build on queries (e.g. subscriptions on subscriptions etc.)

The way we declare subscriptions is in a flat list of `(register-sub..)` which can be namespaced, sure, but the inter-relationships between them is not explicitly captured anywhere.

This issue is a sanity/feasibility check and also a reminder for me when I have some spare time (I checked and there should be some in the next 30 years) to write a parser -> AST -> textual representation to one of the many charting libraries  (http://www.graphviz.org is my goto for this sort of thing).

The `parser->AST` is interesting - I am unsure of whether hooking into `re-frame`'s internals is the right approach or a static analysis of the source code.

Anyway, just a 'wish' at the moment.

**Comment by mike-thompson-day8** [comment]
I'm in the mood to clean up,  so I'm going to close this issue for the moment. I'm a bit doubtful we'll easily find a way forward on this.  Happy to open it again later if proved wrong.
