### ISSUE TITLE
Re-frame should have a github-page

### ISSUE THREAD

**Issue by hkjels** [Day8/re-frame#119]
I mentioned to @mike-thompson-day8 that I can help out with making a github-page for re-frame. This just makes it official :+1: 
Any input will be greatly appreciated, wether it's about the design or what content should be most prominent etc.

**Comment by mike-thompson-day8** [comment]
@hkjels  Thanks for looking into this.  

The content we currently have is: 
   - the tutorial in the README
   - pages currently in Wiki   (minus the ones which are reagent specific)  
   - examples  (already in repo)

Would you be proposing to use a site generation tool?  

Warning: I'm currently pressed for time, probably all the way to Christmas, so responses might be a bit slow on occasion.

**Comment by hkjels** [comment]
I was thinking of doing this in re-frame as an additional example. From the very start I'll just be focusing on the look & feel and how to divide the content for an enjoyable read.

Do you associate re-frame with a color?
And is the name re-frame, reagent and framework merged together or is there some deeper meaning to it?

**Comment by mike-thompson-day8** [comment]
Yes, re-frame comes from the merge of reagent and framework. 

No colour comes to mind. 

You probably know this,  but the sister project is https://github.com/Day8/re-com

**Comment by hkjels** [comment]
Yup! I'll keep you posted on whatever progress I make.

**Comment by hkjels** [comment]
So, I've started an invision-project where I'll be posting screens etc.
For now, I'm just trying to find a mood that suits Re-frame.
Please comment and tell me if it's going in the wrong/right direction.
https://invis.io/QZ4OCKZKG

**Comment by mike-thompson-day8** [comment]
Hey, looks lovely.  I like the "flowing river" one.  

This has always made me smile:  
http://www.amusingplanet.com/2012/09/3-most-impressive-water-bridges-around.html

**Comment by hkjels** [comment]
Haha 😀 Indeed
I have one more mood idea, that I think would suit Re-frame well, but it's a bit more work to put together. If you have a look at [Otto](https://www.ottoproject.io) you can see the kind of mood I'm thinking of. Slightly geeky and illustrated, but clean and easy on the eye.

**Comment by mike-thompson-day8** [comment]
Yeah, I like Otto too. I've always thought about re-frame in a slightly cartoon way.  In fact, in the README I reference this sort of diagram:  https://www.sawater.com.au/__data/assets/image/0004/23566/diag_water_cycle.gif

**Comment by mike-thompson-day8** [comment]
I'm keen to see something more beautiful for re-frame, for sure, but I'm not sure this is going anywhere,  so I'm closing for the moment.
