### ISSUE TITLE
Replaying events

### ISSUE THREAD

**Issue by nowprovision** [Day8/re-frame#123]
When replaying events for debugging purposes where a HTTP server is involved, such as bringing down the initial db payload, how do you recommending handling this so replay is deterministic 

e.g.
[:initialize] -> [:fetch-data] -> [:populate-db data] 

If I replay I don't really want to replay fetch-data from server, as the populate-data event has the payload already captured.

Any thoughts on this? In previous world of .net we'd separate commands and events out, commands would generate events which would make the model changes, the commands might do the non-idempotent stuff like send a welcome email etc.. Although Im rusty so I have no direction on applying this here.

**Comment by danielcompton** [comment]
Great question! This is probably better suited for the ClojureScript or Reagent mailing list. See https://github.com/Day8/re-frame/blob/master/CONTRIBUTING.md#support-questions for more details on these support forums. Also, it doesn't answer your question directly, but take a look at https://github.com/Day8/re-frame/wiki/Talking-To-Servers if you haven't already as it has some thoughts around this.
