### ISSUE TITLE
flux-challenge using re-frame

### ISSUE THREAD

**Issue by jelz** [Day8/re-frame#126]
It's not really an issue, but I don't have a clue how to communicate with re-frame community, so I took the liberty of writing here.

There's [flux-challenge](https://github.com/staltz/flux-challenge) that is actually about exploring UI architectures. I've created a very _raw_ [re-frame version](https://github.com/staltz/flux-challenge/pull/35). I'd be more than grateful for Code Review of more experienced re-frame users.

**Comment by mike-thompson-day8** [comment]
@jelz   thanks for doing this!   I'd suggest posting your work to the re-frame channel in clojurians http://clojurians.net/

I've had a quick look,  and although I don't understand how the app works, it looks about right on the surface. 

I'd probably quibble about a bunch of smaller coding issues .... eg use `mapv`  instead of `(vec (map ...))`  etc.  Happy to give that kind of feedback.  Wondering how to provide it.  Comments on the PR?

**Comment by jelz** [comment]
@mike-thompson-day8 thank you for your response and for re-frame itself :)

The most important thing for me is to provide the solution that's structured and implemented with a compliance with a re-frame way of doing things. I don't want to give a bad press to this great project.

I'm aware that my Clojure coding is far away from being elegant and even proper in some cases, I was dropped into this world not so long ago and it's one of my learning projects. Coding feedback in a form of PR comments will be very much appreciated!

**Comment by mike-thompson-day8** [comment]
Okay, I've done two passes over the code.  

**First**, I've superficially looked over the code from a re-frame point of view, and I can see no glaring problems. Everything looks fine. Having said that, I've not really grocked the purpose of the app itself yet.  So this pass was shallow.

**Second**,  I've also done a pass looking at the code from a pure Clojurescript point of view.  Some notes added to the PR. 

If I have the time, I'll try to grok the purpose of the app, and look more deeply into the re-frame side of things in a couple of days.

**Comment by jelz** [comment]
@mike-thompson-day8 Thank you very much for your Code Review. It took a while for me to sit down and write some code again, but I've finally managed to do it.

I've applied your suggestions to my code. I've also did some refactoring on my own - now the solution uses a handler middleware (`path` simplifies handlers a lot!). I've bumped re-frame to v0.5.0.

PR [is merged](https://github.com/staltz/flux-challenge/tree/master/submissions/jelz). I've added link to [this wiki page](https://github.com/Day8/re-frame/wiki/External-Resources).

Please feel free to close this issue if you don't have anything else to add. Thanks and keep up the good work!

**Comment by mike-thompson-day8** [comment]
@jelz.  Thanks for doing it!

**Comment by mike-thompson-day8** [comment]
Looks like we have an accepted solution.  I'll close this.
