### ISSUE TITLE
minor issue: pure middleware can return nil (reframe 0.4.1)

### ISSUE THREAD

**Issue by genovese** [Day8/re-frame#127]
I'm just starting to use re-frame (the pattern and implementation), and it looks terrific.
The documentation is also really helpful (and rather inspiring to boot).

In looking over the built-in middleware as a model for my own, I noticed a minor issue
and thought I'd mention it.  The end of `pure` (along the main code path) looks like

    (if-not (identical? db new-db)
      (reset! app-db new-db))

which will return `nil` if the handler does not change the database.
I realize that pure is applied as the outermouse layer with `register-handler`,
so this causes no problems in typical use. But on the chance that someone
builds a different registration path using `register-base` or something else
unusual, it seems reasonable (and cost free) to have `pure` conform to 
the expected behavior, with:

    (if-not (identical? db new-db)
      (reset! app-db new-db)
      db)

As I said, a minor issue at most.  

Thanks again.

**Comment by mike-thompson-day8** [comment]
Hey, thanks for the report,  but I'm not sure this is a bug or a required change.  `pure` is always the first middleware. No need for it to return anything.

**Comment by genovese** [comment]
Hi Mike, I did address that issue explicitly in my comment.  But I agree
that that is an unlikely and minor case. No worries. And thanks again.
