### ISSUE TITLE
easily get app-db data in handlers

### ISSUE THREAD

**Issue by jiangts** [Day8/re-frame#131]
I read in the readme that I shouldn't include subscriptions in my handlers.

However, I find this a nice thing to do for two reasons:
1. I'm using `path` middleware in my handlers, and the extra data I want to use in the handler isn't under that path.
2. subscriptions are a succinct, short way for describing data (instead of having to litter my code with the data path everywhere).

Is there a strong reason to not have subscriptions in my handlers?

**Comment by mike-thompson-day8** [comment]
@jiangts  It is an approach will corrupt the architecture. It sounds like your path middleware is too narrow. Or that the data should be a part of the event dispatched.  Or some other design problems.

See FAQ item #1 - https://github.com/Day8/re-frame/wiki/FAQ#1-why-cant-i-access-subscriptions-from-event-handlers

Also please see that this is not the place to be asking these questions:
https://github.com/Day8/re-frame/blob/master/CONTRIBUTING.md#support-questions
