### ISSUE TITLE
Little typo on the testing page

### ISSUE THREAD

**Issue by simax** [Day8/re-frame#136]
In the section that begins...

*We could split the handler function from its registration, like this:*

```
(defn get-completed-count
  [app-db _]
  (reaction (completed-count (:todos @db))))
```

`:todos @db` should be `:todos @app-db`

**Comment by mike-thompson-day8** [comment]
Thanks!  You should be able to directly edit those Wiki pages.  At least I hope you can.

**Comment by simax** [comment]
Oh yeh, duly edited.
