### ISSUE TITLE
Add docs for new features

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame#139]
We need to write docs for dynamic subscriptions, and possibly other new features that have been added that haven't been documented.

**Comment by mike-thompson-day8** [comment]
As far as I'm aware, dynamic subscriptions is the only thing that needs further docs.

**Comment by BenMacKenzie** [comment]
Possibly I'm missing something, but it seems that documentation is missing for very basic features.   Maybe there is a lot of assumed knowledge that I don't have (I'm not a front end developer).  For example, I can't find an example of using  a drop down anywhere.  If there are examples available, it would be great to link to.

this doesn't work properly:

(defn dropdown.
  []
  (fn []
  [:select {:on-change #(re-frame/dispatch [:change-letter (-> % .-target .-selected)])}
    '([:option "a"] [:option "b"] [:option "c"])]))

**Comment by danielcompton** [comment]
@BenMacKenzie re-frame is an application framework, not so much a UI library. You could take a look at [re-com](https://github.com/Day8/re-com) which is a UI library designed to work with reagent.

**Comment by BenMacKenzie** [comment]
Yes, thanks, i think this is what i was looking for.  I'm a total front end newbie...no javascript, no react, no re-agent.

**Comment by mike-thompson-day8** [comment]
I'm going to close this.  The dynamic subscriptions now has first cut docs.  More could be done, but that's always the case.

**Comment by mike-thompson-day8** [comment]
@BenMacKenzie  Support requests and usage questions should go to the Clojure Slack channel (http://clojurians.net/), the ClojureScript mailing list (https://groups.google.com/forum/#!forum/clojurescript), or the Reagent mailing list.
