### ISSUE TITLE
Referencing the alpha in the example

### ISSUE THREAD

**Issue by virmundi** [Day8/re-frame#141]
The alpha is not available in the lein-enabled repos like clojars. This means that I have to build the re-frame alpha project before following the README for the todo example. If I don't do this, the todo example fails to build since the alpha is unknown.

Could you either revise the todo README to say that do build the alpha (trunk version) first or not reference the alpha in the example? That one little change (not referencing the alpha) made it work.

Thanks,
JPD

**Comment by mike-thompson-day8** [comment]
@virmundi  good point!  Thanks.  Well push 0.7.0-alpha to clojars within the hour.
