### ISSUE TITLE
get and set app-db for testing purposes?

### ISSUE THREAD

**Issue by leohahn** [Day8/re-frame#143]
I just started using re-frame. Without re-frame, I use boot-reload/figwheel, so I tend to implement components and update the state on the browser-repl, so I can see the changes immediately.

Since re-frame hides the current app-state, is there a way that I can set it manually or get its value?

**Comment by ShayMatasaro** [comment]
you can have a text box at the bottom of the page that always displays app state , or a button that when clicked logs the atom to the console

**Comment by mike-thompson-day8** [comment]
https://github.com/Day8/re-frame/wiki/FAQ#5-how-can-i-inspect-app-db
