### ISSUE TITLE
Testing Handlers that Dispatch Other Handlers

### ISSUE THREAD

**Issue by alexfaber2011** [Day8/re-frame#144]
First off, I've build two apps with re-frame and have thoroughly enjoyed it. Great work. 

I have a question about how to test handlers that dispatch other handlers (say when fetching from a server).  Here's what the wiki says about fetching from servers

```clojure
(ns my.app.handlers
   (:require [ajax.core :refer [GET POST]]
             [re-frame.core :refer [register-handler]))

(register-handler
  :request-it
  (fn
    [db _]
    (ajax.core/GET
      "http://json.my-endpoint.com/blah"
      {:handler       #(dispatch [:process-response %1])
       :error-handler #(dispatch [:bad-response %1])})
     (assoc db :loading? true)))
```

This approach relies on dispatching another re-frame handler (either `:bad-response` or `:process-response`).

To test the `:request-it` handler the testing section in the wiki tells us to yank out the anonymous function which exposes it for testing like so:

```clojure
(ns my.app.handlers
   (:require [ajax.core :refer [GET POST]]
             [re-frame.core :refer [register-handler]))

(defn request-it
    [db _]
    (ajax.core/GET
      "http://json.my-endpoint.com/blah"
      {:handler       #(dispatch [:process-response %1])
       :error-handler #(dispatch [:bad-response %1])})
     (assoc db :loading? true)))


(register-handler
  :request-it
  request-it)
```

The problem is we're only able to test what `request-it` returns which is an updated version of the app db that has it's `:loading?` flag set to true.  What's the best way to test what's happening downstream, say after `:process-response` or `:bad-response` is called?

**Comment by danielcompton** [comment]
Hi Alex, thanks for the question!. This would probably be better served at one of the sources listed here https://github.com/Day8/re-frame/blob/master/CONTRIBUTING.md#support-questions, these GitHub issues are more for bugs and feature requests. Thanks!

**Comment by alexfaber2011** [comment]
Hi Daniel!  Oops, my mistake.  I'll be sure to head over to the sources you provides.  Thanks.

**Comment by restebanez** [comment]
https://groups.google.com/forum/#!topic/clojurescript/p0lb0xMKBuQ
