### ISSUE TITLE
Lein template for simple example app

### ISSUE THREAD

**Issue by dparis** [Day8/re-frame#15]
I've set up a lein template project for re-frame which emits the simple example app, parameterized with the project name:  https://github.com/dparis/re-frame-template

I know it's still early-days for re-frame, but I thought it'd be nice to help the intrepid few get started easily.

I haven't yet deployed it to clojars, as I wanted to see how you might like to coordinate the release of this. If you'd like to assume ownership of the repo, just let me know and I'll transfer it over. Otherwise, let me know if there's anything you'd like me to update before I push it to clojars.

Can't wait to start using re-frame. Cheers!

**Comment by mike-thompson-day8** [comment]
@dparis  That's excellent, thanks.  I have no experience writing lein templates so this is welcome news.  

But I do have a request  (which is a pain, I'm sure).  Could it be based on the todomvc example currently in develop?   That example splits handlers and subscriptions into different files, etc.  

https://github.com/Day8/re-frame/tree/develop/examples/todomvc

I'm imagining that most of the code can be removed to leave a shell.

I'm planning on releasing v0.2.0 within the next couple of days and this template would icing on the cake whenever it arrives.  on the other hand, I would certainly understand if this was unwanted additional work and you weren't up for it.

Regarding ownership, I'm very happy with either option, although probably happier for you to get the credit and simply link to it from re-frame docs.

**Comment by dparis** [comment]
Yeah, that's no problem. In fact, I can offer one better, if you like:  if there's a generic reference implementation you'd like to collaborate on that only includes base functionality (no todo app logic, no simple example logic, etc) once v0.2.0 comes out, I'd be happy to work on that with you.

The timing might work better for me in that case as well. I just finished two days of jury service and I need to catch up on my day-job work. I'll hold off on changing anything until I've caught up and you've released the next version. At that point we can touch base and make the template better, if you're up for it.

**Comment by mike-thompson-day8** [comment]
@dparis  if you are still up for it, we're now right to go on the lien template, I think.  I'd like to use the TodoMVC as the exemplar. See examples/todomvc.  How should we do this?

**Comment by dparis** [comment]
Ideally I was thinking something like https://github.com/reagent-project/reagent-template but which also sets up a barebones skeleton for the re-flow pattern within the template. Personally I think it would get tedious to have to go through and delete some example code from the emitted project code each time. As such, I didn't intend to include any functionality (todo app, or hello world type stuff, etc) in the final version, just some placeholder comments or function stubs, that sort of thing.

I'd be happy to base the template off the structure from the TodoMVC example, though, and maybe we could include an optional template parameter to have it generate the TodoMVC logic in the emitted project. That seem like the right approach?

As for ownership, I appreciate the sentiment. :smile: However, I'm not sure how much time I'll have to maintain the repo, and I wouldn't want a lack of maintenance to imply that the re-frame project itself is being neglected. Because of how lein automatically picks up templates from clojars, people won't see the dparis part of the repo when using it, just the `lein new re-frame-template`, and might reasonably assume it's an "official" part of the re-frame project. I'd still be happy to be a primary contributor to the project, but it might make more sense for you to hold stewardship over it in case I'm ever unable to keep working on it.

**Comment by gadfly361** [comment]
Just as an aside, @mike-thompson-day8 check out this [repo](https://github.com/tcw/lein-create-template). Basically, it creates a lein-template automatically from a normal application and allows you to name the outputted template whatever you want.  

The only catch is, when you name the template, it will do a global replace all for the original name (including in README, etc.) of the application and replace it with the new template name.  So the following would probably work for you:

1. `$ lein new awesome-template`
2. Set up the template however you want it to look.
3. `$ lein create-template re-frame`
4. `$ lein install` and then push to clojars
5. Now, everyone can enjoy the awesome template with `$ lein new re-frame <name of app>`

**Comment by mike-thompson-day8** [comment]
@gadfly361 Thanks!  that looks interesting. Have you used it successfully?

@dparis yes, I was imagining all the code stripped out of TodoMVC.  I wanted to use it as a base because it had the right structure (files wise).  
I'm happy to assume stewardship responsibility whenever you feel it is the right time.

**Comment by gadfly361** [comment]
@mike-thompson-day8 Yup, works great :)

**Comment by dparis** [comment]
@mike-thompson-day8 Sorry, got swamped a bit at work. Should hopefully have some time to get to this over the weekend.

@gadfly361 Cool tool! I'll have to check that out.

**Comment by dparis** [comment]
Working on this right now, should hopefully have something later this afternoon.

FWIW, I'll be using the todomvc structure within a clean [reagent-template](https://github.com/reagent-project/reagent-template) project install as the template. This will provide both a clean base for re-frame template using todomvc's correct re-frame app structure as well as a turn-key installation of clj/cljs with client-side testing, figwheel for live-updates in the browser, and the ability to bundle a lein-ring standalone jar/war server.

**Comment by dparis** [comment]
Alright, I've got a new branch up with my changes so far:  https://github.com/dparis/re-frame-template/tree/update-re-frame-structure

@mike-thompson-day8 I've tried to leave in the stubs I thought were appropriate, and removed the rest of the todomvc logic. Everything seems to work great in my (admittedly minimal) initial testing. If you want to try it out, clone my repo and, from within the repo root, run `lein new re-frame <project_name>`. This will create emit a new re-frame project in the current directory, and it should behave similarly to a reagent-template project.

One minor gotcha is that the emitted init logic renders the `project.views/project-app` function, which by default is just some static markup. Since figwheel is not set up to re-init the app on code changes, attempting to change the value returned by `project-app` can give the false impression that the figwheel live reloading doesn't work. 

You can work around this by setting up the template to initially render a wrapper div which contains a reactive element, at which point changing the content of that element will, well, cause the page to react. This is similar to what reagent-template does by default. However, it's not core to the structure required by re-frame, and might be undesirable as a default, so I deferred to the logic used by todomvc.

 If there's anything you like to see added or changed, let me know.

**Comment by mike-thompson-day8** [comment]
Sorry, I just realised I dropped the ball on this.  Will have a look tomorrow.

**Comment by mike-thompson-day8** [comment]
WIP happening here:  https://github.com/Day8/re-frame-template/tree/update-re-frame-structure

I've written stuff, but not tested.  Will generate a PR once I actually tried to compile it.  Will be another day.

**Comment by mike-thompson-day8** [comment]
Latest:  https://github.com/dparis/re-frame-template/pull/3

**Comment by dparis** [comment]
Merged, thanks for the PR. I've opened a new PR which includes all of the changes so far to be merged into master:  https://github.com/dparis/re-frame-template/pull/4

Let me know if there's anything else you'd like to see changed before that happens. Once that PR is out of the way, it might be a good time to hand off the project if you're willing, my March/April is starting to look pretty busy.

**Comment by yatesco** [comment]
Can I ask what the current recommended approach for getting started with re-agent is?

**Comment by mike-thompson-day8** [comment]
@dparis As far as I can tell, this is completed.  You just need to accept your own pull request, and announce.  Is there anything else I can help with?

**Comment by dparis** [comment]
@mike-thompson-day8 Sorry for the delay! I'll have some time intermittently this week to work on transferring the repo before I'll be travelling.

As far as I can tell, I can just use the GH repo transfer to hand the entire GH project (repo, issues, etc) over to you. Will that work for you? Is there anything you'd like to see completed before I do so?

**Comment by mike-thompson-day8** [comment]
@dparis when you get a chance, I'm more than happy to take this over.  And, yes, repo transfer seems like the way.  Seems pretty much there as is. More instructions in the README maybe?  Anyway, thanks for pushing it this far!

**Comment by dparis** [comment]
I'll be in airports all day today, so I'll probably get to it tomorrow.
Great work on re-com, by the way, made use of it to knock out a quick ui
for a demo we gave yesterday. :smile:

**Comment by mike-thompson-day8** [comment]
Good to hear that re-com worked for you!!

We're aware that re-com has a smaller audience than re-frame (until this time next year when suddenly re-com will come into its own, I think).  Perversely re-com has involved MUCH more work.   So it is nice to hear of early success.

**Comment by mike-thompson-day8** [comment]
@dparis Thanks for the transfer!!   It now lives here: https://github.com/Day8/re-frame-template.

**Comment by dparis** [comment]
You're welcome! Hope it is, and remains, useful. I'll be watching re-frame and the template, and I'll try to contribute when I can. Let me know if you need anything else. Cheers!
