### ISSUE TITLE
Benefits of subscriptions registering

### ISSUE THREAD

**Issue by BartAdv** [Day8/re-frame#150]
This is just a question, not exactly an issue, but I thought this might be good place to ask:

Registering a subscription means just storing a function that takes app-db and returns a reaction, later on when we call `re-frame/subscribe [:subscription]` we just fetch this function an obtain reaction from it to feed to reagent. What are benefits of all of this? Couldn't we just do without registering and provide the function directly to `subscribe`?

**Comment by martinklepsch** [comment]
Hey @BartAdv. Please take a look at [CONTRIBUTING.md](https://github.com/Day8/re-frame/blob/master/CONTRIBUTING.md#support-questions) to find appropriate support channels. The issues in this project are meant for bug reports and other discussions related to the development of `re-frame`.

**Comment by BartAdv** [comment]
Thanks, somehow I haven't looked into that file.
