### ISSUE TITLE
Make debug middleware diff algorithm "injectable"

### ISSUE THREAD

**Issue by kristianmandrup** [Day8/re-frame#152]
We are currently integrating re-frame with Datascript via the Posh library.
However when we have a DataScript DB as the application state (atom) we can't really do a data structure diff in the classical sense. Please change the `debug` middleware to not depend directly on `data/diff`

```cljs
;; default diff algorithm
(def default-diff data/diff)

(defn debug
  "Middleware which logs debug information to js/console for each event.
  Includes a diff of the db/atom, before vs after, showing the changes
  caused by the event."
  [handler diff]
  (fn debug-handler
    [db v]
    (group "re-frame event: " v)
    (let [new-db  (handler db v)
          diff    ((or diff default-diff) db new-db)]
      (log "only before: " (first diff))
      (log "only after : " (second diff))
      (groupEnd)
      new-db)))
```

**Comment by mike-thompson-day8** [comment]
The goal was always that users would write their own middleware.  Sure, re-frame supplies some standard ones,  but it is very easy to do your own (I could help if necessary). Then users just provide this alternative middleware. 

So, could `posh` just provide to users with its own version of this middleware, called say `posh-debug`?  

What do you think?

**Comment by kristianmandrup** [comment]
Sure, I thought about that as well... but my intuition tells me that is a dangerous road to go down, for portability reasons etc. Better to have more generic middleware IMO and then use a standard vocabulary across different implementations/environments which can be configured as needed. Your thoughts?

**Comment by kristianmandrup** [comment]
https://gitter.im/metasoarous/posh

**Comment by mike-thompson-day8** [comment]
And, just for the record, the code you supplied above won't work because `debug` is a middleware and not a middleware factory. 

https://github.com/Day8/re-frame/wiki/Writing-Handler-Middleware

**Comment by kristianmandrup** [comment]
OK, I'm also only just learning Clojure and ClojureScript... ways to go!
Btw: I love your "middleware" approach (ie. outsideware). Is there a registry I can access to lookup registered handlers, such as for testing purposes using property testing f.ex? I have yet to read the docs/story on testing... but should be a good one!

**Comment by hugobessaa** [comment]
I'm with @mike-thompson-day8 in that posh should provide re-frame middlewares for debugging.

Middlewares like `debug` are specific to the pattern the docs propose to write re-frame apps.

**Comment by mike-thompson-day8** [comment]
I think we got to the end of this.  I'm going to close.
