### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by chris-etheridge** [Day8/re-frame#159]
This is not an issue, so sorry about the pesky notification, but how can I contact Mike Thompson via email?

Thank you!

**Comment by mike-thompson-day8** [comment]
@chris-etheridge rather than email, would you mind contacting me via DM on [Clojure Slack](http://clojurians.net/) ?   I'm @mikethompson on slack.

**Comment by chris-etheridge** [comment]
Of course! Thank you :smile:
