### ISSUE TITLE
Write docs showing new sexier subscriptions approach in v0.3.0

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#16]

**Comment by koddo** [comment]
Is it about using re-frame/subscribe instead of re-frame/register-sub?
```clojure
(let [phone           (re-frame/subscribe [:phone-query phone-id])
      phone-details   (re-frame/subscribe [:phone-details])
      images          (reaction (:images @phone))]
  ;; @phone
  ;; @phone-details
  ;; @images
  )
```

**Comment by mike-thompson-day8** [comment]
@koddo    The next version of re-frame v0.5.0 will have a small tweak to the way subscription handlers are written. That means a small tweak to `register-sub`. 

Mind you, I have been threatening this for about two months now and in the meantime v 0.3 and 0.4 have come and gone.  So don't hold your breath with too much excitement.  :-)

**Comment by mike-thompson-day8** [comment]
I'm going to close this ticket because, better late than never, it has been superseded by #170.
