### ISSUE TITLE
Upgrade - Clojure 1.8 and Clojurescript 1.8.x

### ISSUE THREAD

**Issue by corporatepiyush** [Day8/re-frame#162]
v 1.8 is out there since a while now, its time to upgrade !

**Comment by danielcompton** [comment]
There's not really much benefit upgrading our Clojure and ClojureScript dependencies, your project will use whichever versions of Clojure and ClojureScript you specify, not the version in the re-frame dependencies. We may upgrade at some point, but I don't think there's any new features in 1.8 that we want.

**Comment by mike-thompson-day8** [comment]
Yeah, so just to be clear:  you apps `project.clj` will nominate certain version of Clojure and ClojureScript (1.8 !!), and those dependencies will override anything we put in a library's `project.clj` (like re-frame).
