### ISSUE TITLE
Change middleware/debug to only create a grouped diff when there is actually a diff

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame#166]
It would be helpful for scanning the console if middleware/debug had a different log message when there was no diff. For example I think:

<img width="193" alt="screenshot of google chrome 5-05-16 10-59-15 am" src="https://cloud.githubusercontent.com/assets/811954/15031883/6a5b8d52-12b0-11e6-8012-cbf212634d26.png">

would be more helpful if it was something like

```
clojure.data/diff for: [:my-event "with-val"]: no changes
```

**Comment by arichiardi** [comment]
Big :+1: on this!

**Comment by danielcompton** [comment]
A concrete example of where this is a problem is when you're refactoring. It's not obvious from looking at the logs that your handler which used to do something useful now does nothing.

**Comment by mike-thompson-day8** [comment]
Will be a part of the next release. Closing.
