### ISSUE TITLE
Select component behaves strangely

### ISSUE THREAD

**Issue by restebanez** [Day8/re-frame#168]
Hi,

The below reproduce-select-bug component behaves strangely when the user clicks on an item::

- the item get selected for a few miliseconds
- it selects/highlights a previous one for a few milisecons (this is the bug)
- It goes back to the original selected one

```
(register-sub
  :selection
  (fn [db _] (reaction (get-in @db [:selection]))))

(register-handler
  :set-selection
  (fn [db [_ selection]]
          (assoc-in db [:selection] selection)))

(defn reproduce-select-bug []
      (let [selection (subscribe [:selection])]
           (fn []
               [:div.controls
                [:select.input-large
                 {
                   :value @selection
                   :on-change #(dispatch [:set-selection (-> % (.-target) (.-value)) ])
                   :size 3
                  }
                  '( ^{:key "one" }   [:option {:value "one"}   "one"   ]
                     ^{:key "two" }   [:option {:value "two"}   "two"   ]
                     ^{:key "three" } [:option {:value "three"} "three" ])
                 ]])))
```

If i take out the subscription/dispatch and turn it into a pure reagent component it works fine

```
(defn working-select []
      (let [selection (atom "")]
           (fn []
               [:div.controls
                [:select.input-large
                 {
                  :value @selection
                  :on-change #(reset! selection (-> % (.-target) (.-value)) )
                  :size 3
                  }
                 '( ^{:key "one" }   [:option {:value "one"}   "one"   ]
                    ^{:key "two" }   [:option {:value "two"}   "two"   ]
                    ^{:key "three" } [:option {:value "three"} "three" ])
                 ]])))
```

Any ideas on why it behaves like this?

**Comment by danielcompton** [comment]
Should the `assoc` and `get` in your handler and subscriptions be `assoc-in` and `get-in` respectively?

**Comment by restebanez** [comment]
Yes! i've updated the code but unfortunately the issue remains

**Comment by mike-thompson-day8** [comment]
Code snippets look fine.  But this is not the right place to be discussing this.  

re-frame uses Github issues for bug reports and feature requests. Support requests and usage questions like this should go to the #reagent channel in [Clojure Slack](http://clojurians.net/) or the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript).
