### ISSUE TITLE
Write Wiki docs explaining how to do testing

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#17]
re-frame <s>v0.3.0</s>,  <s>v0.4.0</s> v0.5.0 will allow each of the parts to be nicely tested (all without any async problems).  Or, at least that's the cunning plan.  

Explain how to do each part:
  - db
  - handlers
  - subscriptions 
  - components

**Comment by mike-thompson-day8** [comment]
Not testing, but debugging: 
https://github.com/Day8/re-frame/wiki/Debugging-Event-Handlers

**Comment by gadfly361** [comment]
Looking forward to wiki on testing! The re-frame documentation has been simply awesome so far, thanks for all the hard work.

**Comment by Rodeoclash** [comment]
:+1:

**Comment by mike-thompson-day8** [comment]
See the new Wiki page:  https://github.com/Day8/re-frame/wiki/Testing
