### ISSUE TITLE
Add to README: how to organize as your app gets bigger

### ISSUE THREAD

**Issue by seanhess** [Day8/re-frame#176]
Hi there, coming from React and Elm, and it's not obvious how you recommend organizing a medium sized project. You can't be putting everything in the same db.cljs, handlers.cljs, right? That doesn't scale. I'm looking for the equivalent of [The Elm Architecture](http://guide.elm-lang.org/architecture/).

I'm sure you have a solution for this but I can't find it. Could you point me towards some resource to help, and perhaps add something to the README?

**Comment by seanhess** [comment]
I just found the wiki entry: https://github.com/Day8/re-frame/wiki/A-Larger-App. Consider adding a link in the README?

**Comment by seanhess** [comment]
Huh. That article is pretty short. That approach seems to still require situational awareness at every nested level. For example, let's say I have some handlers that operate on the Current User part of my schema. Why should each of those handlers have to know how to locate the current user in the root-level state? 

Am I just bringing some baggage with me from Elm that doesn't apply? I'd love to hear your take on the Elm Architecture. Is it not necessary here? What are people doing in the real world?

**Comment by danielcompton** [comment]
@seanhess you can use the `path` middleware to scope the data that your handler accepts to a particular path. I think this would work for your particular question, although the larger issue remains.

re-frame is flexible enough that you can structure your app in any way you like. I realise that's not very helpful guidance 😄. We find the panel based approach works well for the kinds of apps that we build, but I'm sure there are other good options too.

**Comment by seanhess** [comment]
Thank you for the guidance. I'll experiment more and post back if I have anything specific to recommend adding to the README.
