### ISSUE TITLE
call to clojure.data/diff in re-frame/debug hogs CPU

### ISSUE THREAD

**Issue by emanjavacas** [Day8/re-frame#188]
I've been experiencing some issues with a largish app I am working on.
Basically after doing a particular type of db update (via re-frame/dispatch) CPU hogs (sometimes up to even 10 seconds). I've been tracing back the cause and it turned out to be the
clojure.data/diff call in the built-in re-frame debug function. I am a bit puzzled because it only happens with that particular update and the db change isn't really that drastic.
Obviously, this isn't a huge problem given that it only happens during development, still I wanted to report it, mostly, for clarification.
I can also point to the code which is causing this.

best,

**Comment by danielcompton** [comment]
Can you provide a reproducible example that takes a long time to update? Just 2 simple handler's that set the old value, then the new one should be adequate.

**Comment by mike-thompson-day8** [comment]
@emanjavacas thanks for the report.  I agree this can be a trap.  But the expensive nature of `debug` is documented in the Wiki.  Will see if I can make it more prominent.
