### ISSUE TITLE
Browser restrictions for actions outside user events? E.g. fullscreen-mode

### ISSUE THREAD

**Issue by AlexAti** [Day8/re-frame#191]
So I want to have an element jump into fullscreen mode, and I followed the usual dispatch / handle event pattern:

````
;;; Helper function
(defn launch-fullscreen [elt]
  (cond
    (.-requestFullscreen elt) (.requestFullscreen elt)
    (.-mozRequestFullscreen elt) (.mozRequestFullscreen elt)
    (.-webkitRequestFullscreen elt) (.webkitRequestFullscreen elt)
    (.-msRequestFullscreen elt) (.msRequestFullscreen elt)))

;;; On the component
        [:a {:class "button"
             :on-click #(dispatch [:fullscreen-video-button-action])}
                       ;Alternative discussed below follows:
                       ;#(launch-fullscreen (aget (.getElementsByClassName js/document "videocanvas") 0))}
           [:i.fi-arrows-out]]

;;; Then the event handling
(defn fullscreen-video-button-action [app [ev-id]]
  (assert (= ev-id :fullscreen-video-button-action))
  (launch-fullscreen (aget (.getElementsByClassName js/document "videocanvas") 0))
  app)
(register-handler :fullscreen-video-button-action fullscreen-video-button-action)
````

The problem is that Chrome tells me: "Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture.". I guess it is a browser security measure so an app can't do nasty things without you noticing (Firefox and Safari also reject it in the same vein, btw).

As one would expect, if I then do what the error says, and call the function in the element (as in the commented alternative to the dispatch fn in the code above), it works.

Is this a limitation of the re-frame pattern, or is there a way I can separate my code from the component, that works with these kind of things?

**Comment by marctrem** [comment]
Random guess, have you tried `dispatch-sync`?

**Comment by AlexAti** [comment]
Yes, that fixes it! Thanks!
