### ISSUE TITLE
Logging is a bit invasive

### ISSUE THREAD

**Issue by arichiardi** [Day8/re-frame#195]
I get a lot of `Using cached...` in the logs and given I am already using `trace-forms`, this causes a little bit of mess in the console.

I was wondering if there is a way to disable [this](https://github.com/Day8/re-frame/blob/311367dc3d2189c148464886f5ef2c9de473480d/src/re_frame/subs.cljc#L58) for instance or if they will just go away with the new release `0.8.0`.

The rest seems very smooth, we are using the `reg-sub` facility and I confirm it works and looks great!

**Comment by danielcompton** [comment]
I wonder if logging these should be a closure-defines option?

**Comment by arichiardi** [comment]
Probably it should, at the moment I have two:

```
:closure-defines {"goog.DEBUG" true
                            "clairvoyant.core.devmode" true}
```

so a third one for re-frame would be nice as well.

**Comment by mike-thompson-day8** [comment]
logs should now be clean.
