### ISSUE TITLE
Completely new to re-frame; don't understand the README

### ISSUE THREAD

**Issue by domgetter** [Day8/re-frame#229]
I'm trying to follow along in the README, and was trying to create a subscription handler for `:name-query`.

```
(defn name-query [db [sid]]
  (assert (= sid :customer-query))
  (reaction (get-in @db [:name])))

(re-frame.core/register-sub :name-query name-query)

(defn app-root []
  (let [name-ratom (subscribe [:name-query])]
    (fn []
      [view @name-ratom])))
```

At this point, I get a warning that register-sub is deprecated and I should use reg-sub-raw.

```
(defn name-query [db [sid]]
  (assert (= sid :customer-query))
  (reaction (get-in @db [:name])))

(re-frame.core/reg-sub-raw :name-query name-query)

(defn app-root []
  (let [name-ratom (subscribe [:name-query])]
    (fn []
      [view @name-ratom])))
```

And now I'm getting all sorts of weird errors.  Here's one:

```
console.error: "reframe: no ", ":event", " handler registered for" ", {"ns":null,"name":"name-query","fqn":"name-query","_hash":"780334378,"cljs$lang$protocol_mask$partition0$":2153775105,"cljs$lang$protocol_mask$partition1$":4096}
```
  I am utterly lost at this point, and I would appreciate it if you could point me in the right direction.  Am I going completely insane, or has the code changed such that the README is confusing?

Also, is there anywhere I can read up on "app-db"?  If I ask for app-db in the repl, I get nil back, but your README states that it exists for me in the background?  Any info on this would be appreciated as well.

**Comment by m9dfukc** [comment]
You might look into the new [docs section](https://github.com/Day8/re-frame/tree/master/docs) ... there's also a FAQ dealing with how to [inspect app-db](https://github.com/Day8/re-frame/blob/master/docs/FAQs/Inspecting-app-db.md).

**Comment by domgetter** [comment]
Thank you very much, that helps a lot.

**Comment by mike-thompson-day8** [comment]
Sorry about that:  version 0.8.0 introduced `reg-sub` and the docs haven't yet caught up.  To understand `reg-sub` look at the todomvc example:  
https://github.com/Day8/re-frame/blob/master/examples/todomvc/src/todomvc/subs.cljs
