### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by deg** [Day8/re-frame#232]
At the end of [https://github.com/Day8/re-frame/wiki/Debugging](https://github.com/Day8/re-frame/wiki/Debugging), there is a section "Macro Help".  The links in it are all broken, apparently because refheap.com has gone non-responsive.

**Comment by mike-thompson-day8** [comment]
Quick Note:  all Wiki documentation is being transferred to within the `/docs` folder.  
https://github.com/Day8/re-frame/blob/master/docs/Debugging.md

But, yes,  those links are currently down due to a server 500 error.  I'm assuming they will return soon (they worked a week ago).

**Comment by deg** [comment]
Rumor has it (as heard on the #clojure IRC chanel) that the refheap site is down permanently.

I just tried searching on archive.org too, but no luck.

**Comment by mike-thompson-day8** [comment]
@mccraigmccraig your refheap links [at the bottom of this document](https://github.com/Day8/re-frame/blob/master/docs/Debugging.md)  have gone south.   It looks like refheap has gone dark. 

Any chance you can supply some alternative ones?  Gists perhaps?

**Comment by si14** [comment]
I've just added a PR to inline those snippets #238

**Comment by mccraigmccraig** [comment]
ha, awesome @si14 - i wasn't doing very well at paying any attention to this !

**Comment by smahood** [comment]
PR has been merged to `Develop` branch.
