### ISSUE TITLE
Bug:  doesn't report a missing effects handler

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#237]
If an event handler returns an effect for which there is no registered effect handler, then (currently) that effect is silently ignored.  Which is bad.  There should instead be a cacophony of Bugle noises and many flashing lights.  

https://github.com/Day8/re-frame/blob/master/src/re_frame/fx.cljc#L37-L38

**Comment by kp2222** [comment]
I took a quick look and it looks like the "get_handler" function in registrar prints out console message when it encounters a missing effect handler. 
do you think anything else needs to happen other than this error message? Let me know I am interested in working on this.

**Comment by danielcompton** [comment]
@kp2222 probably a good thing to do here is to write a test that rebinds the loggers, and checks what happens when an effect is emitted that doesn't have a registered fx handler.

**Comment by kp2222** [comment]
Does this test simulate the scenario accurately (#252 ) ?

**Comment by danielcompton** [comment]
Pretty close, I've added some more code to your PR to fix it up and have merged the test. re-frame warns on missing effect handlers now. Thanks!
