### ISSUE TITLE
Clarify if `after` calls `f` when there's no `:db`

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#239]
Currently, the comment on the `after` Interceptor is as follows: 
```clj
(defn after
  "Interceptor factory which runs a given function `f` in the \"after\"
  position, presumably for side effects.

  `f` is called with two arguments: the `effects` value of `:db` and the event. It's return
  value is ignored so `f` can only side-effect.

  Example use:
     - `f` runs schema validation (reporting any errors found)
     - `f` writes some aspect of db to localstorage."
  [f]
  ....)
```
It does not say what happens when `:db` is not present in `:effects`. This [situation is quite legal](https://github.com/Day8/re-frame/blob/master/docs/Effects.md#db-not-always-needed).  In which case, should `after` call `f` if `:effects` has no `:db`, or not?

The current implementation of `after` will always call `f` with the value of `:db`, even if that value is `nil` (because it doesn't exist).   So,  `f` must internally handle being called with `nil`. But this isn't documented. 

From here, two apparent choices ...
   1. the docs be updated to confirm the current implementation (as described above) or  ..
   2. the behavior of `after` should be changed so that it only calls `f` when there is a `:db` key present in `:effects`.  So `f` can never be called with `nil`.  But this might then require another interceptor for the case that  something needs to happen "after" irrespective of the presence of a new `:db`.  Two similar interceptors so similar almost seems untidy duplication.

**Comment by danielcompton** [comment]
What about passing in the old db value, if there is no new one?

**Comment by mike-thompson-day8** [comment]
> What about passing in the old db value, if there is no new one?

Yeah, that's a very valid 3rd option.
