### ISSUE TITLE
Add a :dispatch-throttle effect

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame#250]
Throttle is a sibling to debounce, and they share many similarities. I would gladly take a PR for a `:dispatch-throttle` effect. Requirements:
- Behaves like a throttle, e.g. https://css-tricks.com/debouncing-throttling-explained-examples/, https://lodash.com/docs/4.16.4#throttle
- Takes a map of effects, or a sequence of maps (the same as #249)
- Takes the same map options as `:dispatch-debounce`, with the addition of `:leading?` and `:trailing?` which behave the same as in lodash's [throttle](https://lodash.com/docs/4.16.4#throttle). `timeout` is renamed to `window-duration`
- Tests (the ones written for `:dispatch-debounce` in `re-frame.fx-test` are probably a good start)
- Docs

I'm happy to help with docs and tests, the tricky part which I don't have time for right now is the throttling implementation.

**Comment by kp2222** [comment]
I have created a pull request #258 

The changes are mostly based on #249. Please feel free to suggest anything that needs change

**Comment by danielcompton** [comment]
Closing as we've decided that this probably belongs in a separate lib, more details in https://github.com/Day8/re-frame/pull/258#issuecomment-262658598.
