### ISSUE TITLE
Use case for specific order of side-effects

### ISSUE THREAD

**Issue by IsaacKhor** [Day8/re-frame#253]
After the user clicks on a new item, these things need to happen in this specific order:

1. Save codemirror state to database
2. Change `:active-item-id` to the new id
3. Read state from database and write it to codemirror

Yes, I can work around it if I did some magic with `previous-active-item-id` and `should-write-to-database`, but allowing a specific order for side-effects will be a far cleaner solution.

EDIT: by database I mean `re-frame.db/app-db`

**Comment by mike-thompson-day8** [comment]
@IsaacKhor I have questions:
  -  step2 involves writing to app-db too, right?  (at the same time as step 1)
  - won't step 3 involve delivering data from app-db to a view via a subscription? And be [handled like this](https://github.com/Day8/re-frame/blob/master/docs/Using-Stateful-JS-Components.md). 

If so, then I don't think there's a usecase?  Instead it looks like `app-db` has to be updated (with two pieces of state) and then subscriptions have to send that state through to a view.

**Comment by IsaacKhor** [comment]
Eventually the codemirror state will be written out to the filesystem (to be implemented), so step 1 will need to happen before 2 and 3.

Step 3's current implementation: 

```
(r/reg-event-fx
  :new-active-item
  (fn [{:keys [db]} [_ id]]
    {:dispatch [:save-editor-value (:editor db)]
     ; :dispatch [:write-file-to-fs (:active-item-id db)] ; (not implemented yet)
     :db (assoc db :active-item-id id)
     :set-editor-value [(:editor db) (get-in db [:items id :content])]}))
```

Since the data flows from codemirror->database, not the other way around, a subscription from database to codemirror state makes no sense. When the user types stuff into codemirror, it updates its internal state, and fires `change`, which fires `(r/dispatch :save-editor-value)`.

**Comment by mike-thompson-day8** [comment]
So step 1 is async?

**Comment by IsaacKhor** [comment]
Oops, that's a bug. Step 1 shouldn't be async. New implementation:

```
(r/reg-event-fx
  :new-active-item
  (fn [{:keys [db]} [_ id]]
    {:dispatch-sync [:save-editor-value]
     :dispatch [:write-item-to-fs (:active-item-id db)]
     :db (assoc db :active-item-id id)
     :set-editor-value [(:editor db) (get-in db [:items id :content])]}))
```

The important thing is that the current value of codemirror should be read and put into the database before we change the value of codemirror to a new one.

If it makes it more clear, this is what needs to happen, in this order:

1. I type `(println "hello world")` into codemirror instance. Current cm state: `(println "hello world")`. Current db: `{:content1 "" :content2 "(println \"hello a second time\")"}`
2. `:new-active-item` is fired.
3. cm state -> db: cm state: `(println "hello world")`, db: `{:content1 "(println \"hello world\")" :content2 "(println \"hello a second time\")"}`
4. Dispatch write-to-fs event (this is async and not order-dependent; it doesn't matter when this happens as long as it eventually does)
5. Update db's `:active-item-id` (this just needs to happen after step 1
6. Read from db `:content2` and write to cm: cm state: `(println "hello a second time")`, db doesn't change

The order of 5/6 doesn't matter, as long as it happens after step 1. Does this make sense?

**Comment by IsaacKhor** [comment]
Actually, this is solved by just telling step 3 where to write cm state. However, step 6 still needs to happen after 3, since we need to save the current value of cm before we overwrite it with the new state.

**Comment by IsaacKhor** [comment]
I accidentally solved this issue by rewriting other parts of the application, closing issue.
