### ISSUE TITLE
Information about subscription-handlers in the README is misleading

### ISSUE THREAD

**Issue by idmit** [Day8/re-frame#261]
The README states that subscription-handlers get `db` as a ratom and all examples dereference it with `@db`.

I also got an impression that I need to wrap results of subscription-handlers in a `reaction` call.

All of this doesn't work this way though, as far as I can tell. Is it addressed in some way already?

**Comment by mike-thompson-day8** [comment]
@idmit Sorry those docs were made out of date by release v0.8.0.   I am working on the replacement docs but taking longer than expected.  To understand `reg-sub` please read through:
https://github.com/Day8/re-frame/blob/master/examples/todomvc/src/todomvc/subs.cljs

**Comment by idmit** [comment]
No worries, if it's a known issue, I'll close it 👍

**Comment by idmit** [comment]
Oh, I was already using reg-sub. It's all clear now, thank you.
