### ISSUE TITLE
Add new kind of dispatch fx -  `:dispatch-after-DOM-flush`

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#262]
Not sure about the name but here's the purpose ... 

At the moment, if you want to "pause" the processing of an event until after the DOM is flushed, then you must do this:
```
  (dispatch ^:flush-dom [:event-id param1 ...])    ;; note metadata in the event
```
You are saying ... I want this event processed but only AFTER the next animation frame has had a chance to update the UI.

Normally, you use this when an event handler will hog the CPU for a while, and you'd like the GUI updated first, with a spinner or other explanation, because once the CPU hogs starts, the UI won't get a look in for a while. 

Except normally, this kind of thing happens via effects:
```
(fn an-fx-event-handler 
  [{db :db}   event] 
  {
    :db   (assoc db  :put-up-spinner  true)
    :dispatch  ^:flush-dom [:event-id param1]})     ;; note metadata
```

So .. the proposal is to add an `fx` handler so that this can be done:
```
(fn an-fx-event-handler 
  [{db :db}   event] 
  {
    :db   (assoc db  :put-up-spinner  true)
    :dispatch-after-DOM-flush [:event-id param1]})     ;; <--- new
```
Worth it?

**Comment by mike-thompson-day8** [comment]
Having written up this issue I'm now having 2nd thoughts about it.  

We're talking:
  `:dispatch  ^:flush-dom [:event-id param1]`
vs
  `:dispatch-after-DOM-flush [:event-id param1]`

Almost doesn't seem worth it.

**Comment by stumitchell** [comment]
I think it is more a question of the right way of doing things rather than saving characters. Having this done via effects nicely ties in with `dispatch` `dispatch-n` `dispatch-later` etc plus it means you don't have to worry about meta data and things like

```
(def e [:event-id param1])
...
:dispatch ^:flush-dom e
```

which doesn't work

**Comment by jensontech** [comment]
I have an issue with "flush-dom" - it does not tell the user why you would want to do that. I would prefer something like -
e.g. `:dispatch-after-yield-to-browser [:event-id ...]`
Maybe someone can suggest something with fewer words.

**Comment by danielcompton** [comment]
What we're trying to achieve is dispatching in the next task, so maybe something like `:dispatch-in-next-task`?

**Comment by stumitchell** [comment]
dispatch-after-render

**Comment by bogdan-dumitru** [comment]
If there's still interest in this I'd try my hand at a PR. I also agree with it being more about explicit intent and usefulness, rather than saving chars per se.

> Disclaimer: I'm pretty new to both re-frame and cljs but I'll do my best.

**Comment by mike-thompson-day8** [comment]
After further thought, I'm less keen on this proposal.  Adding the metadata is slightly more manual, but it provides the greatest flexibility.  Closing.
