### ISSUE TITLE
Feature request: new syntax for interceptors

### ISSUE THREAD

**Issue by kana-sama** [Day8/re-frame#265]
What do you think about new interceptor's creation and injection syntax, their registry and a separate file? I can (want to) do it myself, but it is pointless, if it isn't to your taste.

Some advantages:
- no differences in injection syntax between interceptors and interceptor factories;
- familiar sugar for injection and registration;
- it is easier to detect list of interceptors, it's length, order;
- no refers in require.

```clojure
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; interceptors.cljs

;; full
(reg-interceptor :log
  (fn [[prefix]]
    {:before
     (fn [context]
       (println prefix "before")
       context)
     :after
     (fn [context]
       (println prefix "after")
       context)}))

;; short (autowrap it to clojure.core/constantly)
(reg-interceptor :trim-v
  {:before
   (fn [context]
     (update-in context [:coeffects :event] subvec 1))})
```

```clojure
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;; events.cljs

;; reg-event's will accept old vectors too + new inject syntax
;; (like dependencies for subs, but in the opposite direction (like pipes)).
;; Maybe >> or >>> will be better.
(reg-event-db :delete-item
  :-> [:log "system#"]
  :-> [:path :items]
  :-> [:trim-v]
  (fn [items [id]]
    (dissoc items id)))
````

Sorry for my language 🌚

**Comment by mike-thompson-day8** [comment]
I can see why this might be attractive, but I'm not going to include it into core re-frame. 

But, as I'm sure you are aware, re-frame already provides the building blocks that would allow you to do this yourself  right now.

But please do not be put off. New ideas are good!
