### ISSUE TITLE
console.log on IE does not inherit from Function - cannot bind

### ISSUE THREAD

**Issue by minikomi** [Day8/re-frame#266]
[Source](http://stackoverflow.com/questions/14233258/why-cant-i-bind-directly-console-log-on-ie9-with-developer-tools-open)

I'm trying to use re-frame with Internet Explorer 9 (yes, yes I know I know..) and the logging functions trip it up. Quickly replacing [these loggers](https://github.com/Day8/re-frame/blob/master/src/re_frame/loggers.cljc#L19-L27) completely when console.log.group does not exist ala:

``` clj
(def ^:private loggers
  "Holds the current set of logging functions.
   By default, re-frame uses the functions provided by js/console.
   Use `set-loggers!` to change these defaults
  "
  (atom #?(:cljs
           (if (.-group js/console)
             {:log      (js/console.log.bind   js/console)
              :warn     (js/console.warn.bind  js/console)
              :error    (js/console.error.bind js/console)
              :group    (js/console.group.bind js/console)
              :groupEnd (js/console.groupEnd.bind js/console)
              }
             {:log      #()
              :warn     #()
              :error    #()
              :group    #()
              :groupEnd #()
              }))

        ;; clojure versions
        #?(:clj {:log      (partial log :info)
                 :warn     (partial log :warn)
                 :error    (partial log :error)
                 :group    (partial log :info)
                 :groupEnd #()})))
```

is a quick fix. You lose logging on IE9, but at least it works.

**Comment by mike-thompson-day8** [comment]
I notice there's already code in re-frame which tries to handle IE's lack of `group` , here: 
https://github.com/Day8/re-frame/blob/master/src/re_frame/loggers.cljc#L22-L27

I'm happy to take a PR which means re-frame better caters for IE but I'd like to fix what's currently there, rather than taking a sledge hammer to it.  Can you figure out why that current code isn't working and provide a PR for the fix  please.

**Comment by minikomi** [comment]
The current code isn't working, because [the console object on earlier versions of IE does not inherit from Function](http://stackoverflow.com/questions/14233258/why-cant-i-bind-directly-console-log-on-ie9-with-developer-tools-open), and therefore there's no `bind` method.

There's quite a few ways to get around this when dealing with JS.. I'll have a look around and have a think about which one we can slot in here.

EG.

http://stackoverflow.com/questions/5538972/console-log-apply-not-working-in-ie9

```js
Function.prototype.bind.call(console.log, console);
```

**Comment by minikomi** [comment]
I think this can be closed -- it's not worth thinking about just for IE9, which can be solved with a conditional statement and using:

``` javascript
if (Function.prototype.bind && window.console && typeof console.log == "object"){
    [
      "log","info","warn","error","assert","dir","clear","profile","profileEnd"
    ].forEach(function (method) {
        console[method] = this.bind(console[method], console);
    }, Function.prototype.call);
}
```

If need be.

**Comment by mike-thompson-day8** [comment]
Righto. Thanks. Closing.
