### ISSUE TITLE
Ordered effects

### ISSUE THREAD

**Issue by efraimmgon** [Day8/re-frame#267]
It seems ordered effects are necessary for stateful js libs, like google maps, for instance.

Perhaps there's a pattern where ordered effects aren't necessary, but since I'm not aware of any, [here's what I do](https://github.com/efraimmgon/pmmt-cljs/blob/master/src/cljs/pmmt/components/map.cljs):

I have to render some markers on a gmap on a user's request. The markers are stored in a vector on app-db. But on each re-render, I have to clear the previous markers from the gmap, which means I have to first clear the markers stored on app-db before storing new ones.

My current workaround is clearing the markers' state as I  query the server for new data for the markers. In other words, the markers on gmap are cleared whether or not the server query was successful or not This seems wrong to me, but as stated in the beginning, I couldn't think of a better way of solving this problem, unless there are ordered effects.

**Comment by mike-thompson-day8** [comment]
Sorry, I'm not following your description. And there's a lot of code in that link.

**Comment by mike-thompson-day8** [comment]
In the absence of further information from you, and because of a maniacal desire to clean up old issues before v0.9 gets released, I'm going to close this.  But I'll be very happy to reopen if you can come up with that example.
