### ISSUE TITLE
Inconsistent behaviour of def-sub-raw with reaction parameters

### ISSUE THREAD

**Issue by oliyh** [Day8/re-frame#277]
Hi,

Firstly thanks for all your awesome work on re-frame, I really enjoy using it.

I've found some behaviour which surprised me when using `def-sub-raw`. I am using the pattern suggested in https://github.com/Day8/re-frame/blob/master/docs/Subscribing-To-External-Data.md to talk to the server to populate some data when a subscription is made but there is no data in `app-db` to satisfy it.

I find that the 'outer' fn is run multiple times, when I would only expect it to be run once due to the caching / deduplication of subs. Because my outer function has a side effect of talking to the server, this is undesirable.

This code demonstrates the difference in behaviour:

```clojure
cljs.user> (require '[re-frame.core :as re-frame])
cljs.user> (require '[reagent.ratom :as reagent])
cljs.user> (re-frame/reg-sub-raw
            ::foo
            (fn [db _ [some-reaction]]
              (println "Running outer foo" (count @db) (count some-reaction))
              (reagent/make-reaction (fn []
                                       (println "Running inner foo" (count @db) (count some-reaction))
                                       [(count @db) (count some-reaction)]))))
cljs.user> (def f (re-frame/subscribe [::foo] [(reagent/atom [1 2 3 4])]))
#'cljs.user/f
cljs.user> @f
Running outer foo 16 4
Running inner foo 16 4
[16 4]
cljs.user> @f
Running outer foo 16 4
Running inner foo 16 4
[16 4]
```

You see that the 'outer' fn is called on each deref, but the inputs and the outputs are the same.

Compare this with a sub that is essentially the same but does not have reactions passed into it:

```clojure
cljs.user> (re-frame/reg-sub-raw
            ::bar
            (fn [db _ _]
              (println "Running outer bar" (count @db))
              (reagent/make-reaction (fn []
                                       (println "Running inner bar" (count @db))
                                       [(count @db)]))))
cljs.user> (def b (re-frame/subscribe [::bar]))
Running outer bar 16 ;; <-- this is called eagerly
#'cljs.user/b
cljs.user> @b
Running inner bar 16
[16]
cljs.user> @b
Running inner bar 16
[16]
```

The second one only runs the side effect once, and eagerly too, pretty much as I'd expect.

In both cases none of the inputs (db or ratom) have changed.

Is this expected behaviour? And if it is, could you explain why? I would expect and prefer both to behave like the `bar` example.

Thanks!

**Comment by oliyh** [comment]
After thinking about it a bit more, I can understand that `foo` might decide it needs to run the outer fn whenever db or the reaction parameters change, because... Well, they change and it should react to that.

However, if neither have changed, as in my example, it shouldn't run the outer fn. And it still behaves inconsistently with `bar`, I'm guessing because of the fact that the reaction parameters are dereffed by re-frame but the db is not. Essentially it's saying I have reaction parameters so I need to keep re-running the whole (outer) fn to work out any changes, but because db is provided as an atom not a value we would normally just use `reagent/make-reaction` and never have to run the outer fn again.

If that's true, should reg-sub-raw not deref reaction parameters, in the same way that it doesn't deref `app-db`?

**Comment by mike-thompson-day8** [comment]
@oliyh sorry I'm so late to this.  Did you get it resolved?  It seems puzzling.

**Comment by oliyh** [comment]
Hi @mike-thompson-day8

I think what I'm saying is that, if `def-sub-raw` gets the `db` atom and not the value, then it should also get the reactive arguments as atoms, not values. This would let you write efficient reactions and you'd only need to run the outer fn once.

At the moment, with a mix of atoms and values, re-frame keeps running the outer-fn for me but with `def-sub-raw` I'd expect to have all that control myself.

`def-sub` should be all values, `def-sub-raw` should be all atoms.

What do you think?

Cheers

**Comment by mike-thompson-day8** [comment]
The need for dynamic subscriptions has virtually disappeared.  So I'm going to close this.
