### ISSUE TITLE
Incorrect link in README for the cpu hog problem

### ISSUE THREAD

**Issue by gokulj** [Day8/re-frame#28]
In the section 'CPU Hog Problem', the link should be to 
https://github.com/Day8/re-frame/wiki/Solve-the-CPU-hog-problem
instead of to 
https://github.com/Day8/re-frame/wiki/The-CPU-Hog-Problem

**Comment by hura** [comment]
https://github.com/Day8/re-frame/pull/26

**Comment by mike-thompson-day8** [comment]
Thanks, corrected in the upcoming v0.3.0

**Comment by mike-thompson-day8** [comment]
Many Thanks.
