### ISSUE TITLE
Submit re-frame for Rails Girls Summer of Code

### ISSUE THREAD

**Issue by plexus** [Day8/re-frame#284]
Rails Girls Summer of Code (RGSoC) is a yearly program to get more women into open source by awarding selected teams with a two month scholarship to work on a project.

Project submissions are open until end of January, and I'd love to see re-frame participate. You can read all about the process and requirements here.

http://railsgirlssummerofcode.org/guide/projects/

A project needs to provide a mentor, someone familiar with the project, ideally a core contributor, who can answer questions about the project. You also need to prepare a list of potential tasks/features that the team could work on. 

RGSoC will provide the team with coaches for day-to-day coaching, and with a supervisor who forms the link back to the RGSoC organization and keeps an eye on the overall process and progress.

Questions to be answered
- is there general interest to make this happen?
- who can be the mentor?
- what would be good tasks to work on?

**Comment by plexus** [comment]
To clarify, since this might cause confusion, Rails Girls Summer of Code grew out of the Rails Girls movement, but has no particular ties to Ruby or Rails. In other words: any project can participate as long as it has an open source license, a code of conduct, and enough community to support the team.

**Comment by danielcompton** [comment]
Hi @plexus, thanks for bringing this up, I wasn't aware of it. I've submitted re-frame [here](https://teams.railsgirlssummerofcode.org/projects/125-re-frame).

> Is there general interest to make this happen? Who can be the mentor?

Yep, I've talked with Mike Thompson, and he and I are happy to mentor.

> What would be good tasks to work on?

There is a tracing/devtools project we've been working on which would be the main project the team would work on, along with docs, docstrings, error messages, e.t.c.

**Comment by plexus** [comment]
Awesome @danielcompton! I really hope re-frame makes the pick. Also great that you and Mike want to mentor, I would have offered myself as a backup, but an actual core team member is always better, plus I'm not yet sure of my availability this summer.

Let me know if there's anything I can do to help. I know quite a few of the people organizing RGSoC and I've been a supervisor twice before, so I'm happy to answer questions.

**Comment by danielcompton** [comment]
I'm very happy to announce that we have a team of two talented developers working on re-frame for the Rails Girls Summer of Code! They'll be starting work on 1 July. Thanks for the prod @plexus, I'm really looking forward to this.

https://railsgirlssummerofcode.org/blog/2017-05-22-teams-2017
