### ISSUE TITLE
java.lang.Exception: namespace 'reagent.debug' not found

### ISSUE THREAD

**Issue by kanwei** [Day8/re-frame#285]
Switched from 0.8.0 to the new 0.9 betas and suddenly am getting this error. Interestingly, it seems to be coming from the clj side and not the cljs side, since the error happens when loading a clj file (a web controller). Anyone else getting this? Simply switching back to 0.8.0 and everything works again. Not sure what's happening.

Using boot.

**Comment by danielcompton** [comment]
Can you share a minimal reproducing case?

**Comment by danielcompton** [comment]
Fixed. Thanks for the report!

**Comment by kanwei** [comment]
Awesome! Thanks for taking care of this.
