### ISSUE TITLE
out of date lifecycle-functions documention

### ISSUE THREAD

**Issue by pbaille** [Day8/re-frame#298]
https://github.com/Day8/re-frame/wiki/When-do-components-update%3F#lifecycle-functions

This paragraph looks out of date.

After some experiments: @kauko: "So I guess the end result is, if the component doesn't get props (which is the first argument), `component-will-receive-props` and `should-component-update` is never called."

**Comment by danielcompton** [comment]
cc: @Gregg8 I think you noticed this too?

**Comment by mike-thompson-day8** [comment]
That document has now been moved to be with Reagent's  `/docs`, so the link is now:
https://github.com/reagent-project/reagent/blob/master/docs/WhenDoComponentsUpdate.md#lifecycle-functions

As far as I'm aware that paragraph is still valid.  I'm not aware that the first argument is special WRT lifecycle methods.
