### ISSUE TITLE
Yes! #2

### ISSUE THREAD

**Issue by rej156** [Day8/re-frame#3]
Currently finishing off the "http://www.amazon.com/Constructing-User-Interface-Statecharts-Horrocks/dp/0201342782" book due to the indepth ReadME posted.
I too have had that 'click' with regards to all these funky words I've been listening to lately.
I'm going to refactor the whole of my dissertation done in pure reagent/reagent forms because of your framework.

Better yet, I'm going to have actual documentation and a walkthrough that includes statecharts!
I can't say thank you enough.
My dissertation is a "Positive Psychology and Wellbeing mobile web application" which is a bit ironic.
It's basically a reactive text based flow application presenting the user with the next three options to work on their lowest scored core life areas.

Being in my final year, I would also love to learn off you (lot?) or help out in any way possible!

**Comment by mike-thompson-day8** [comment]
@rej156 I'm delighted the readme was helpful.  We should have re-frame through to beta in a few days. 

I'll be interested to hear how you go with statecharts!!

**Comment by mike-thompson-day8** [comment]
@rej156  Be sure to look in this direction:  https://github.com/ztellman/automat

**Comment by mike-thompson-day8** [comment]
@rej156  As you experiment with statecharts, please keep this repo in mind.  We're about to add a couple of sample projects.  In due course, I'd like to include a statechart-using example. Once you have made some progress perhaps you'd consider supplying an example showcasing your approach.
