### ISSUE TITLE
possible copy/paste error in on-changes interceptor

### ISSUE THREAD

**Issue by bskinny** [Day8/re-frame#303]
I was just eyeballing std_interceptors.cljc and noticed the on-changes interceptor has the id of :enrich, as opposed to :on-changes. See line 273. This seems incorrect but I could be mistaken.

**Comment by mike-thompson-day8** [comment]
Yep, this line should be `:id   :on-change`
https://github.com/Day8/re-frame/blob/master/src/re_frame/std_interceptors.cljc#L273

But not a critical fix, because `:id` is pure decorative.

**Comment by bskinny** [comment]
Thanks Micheal.

**Comment by mike-thompson-day8** [comment]
Fixed in 209470e76130eb234acac46b9bedfc51bbeec0ab
