### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by si14** [Day8/re-frame#305]
Google Summer of Code mentoring organization application will open on January 19th. Do you think it may be helpful to participate in it? In practice it will mean that the project will get a (potentially) sizable contribution in exchange for mentoring a student.

If I understand correctly, there are two ways of participating: either directly applying to Google, or taking part in Clojure's bid, though I'm not sure that the latter is possible for non-core projects.

**Comment by danielcompton** [comment]
Hi @si14 

Theres #284 already for Rails Girls SoC as one option for interested people. However their requirements are quite high (2 people in same city + 1-2 mentors in that city). Also, [not everyone is eligible to apply](http://railsgirlssummerofcode.org/students/application/#eligibility).

The GSoC application process looks fairly involved, with a high risk of not getting in (I seem to remember Clojure not getting in in recent years). If someone (you?) was really keen to do GSoC on re-frame then Mike and I would consider making an application, but I think we're unlikely to put the work in without initial interest from a student.

Thoughts?

**Comment by si14** [comment]
@danielcompton unfortunately I'm not a student anymore :) However, I can try to navigate the application process and/or help with mentoring.

Regarding the initial student, do you think it's feasible to announce a tentative opportunity to work on re-frame during GSoC on Clojure mail list?

**Comment by danielcompton** [comment]
Hey, I think we missed the boat on GSoC this year, but RGSoC is going ahead!
