### ISSUE TITLE
Monadic subscription handlers

### ISSUE THREAD

**Issue by glittershark** [Day8/re-frame#324]
Currently, subscriptions with `reg-sub` form an applicative functor with respect to input signals - mulitple input signals can be "fanned in" to a function that takes the same number of parameters, and returns a raw constant value. I was thinking it'd be nice if they were monads as well - essentially, if I could pass the contents of one subscription reaction as parameters to another subscription.

**Comment by danielcompton** [comment]
> if I could pass the contents of one subscription reaction as parameters to another subscription.

Can you clarify what you mean by this? Maybe with some sample code to show roughly how this would look?

**Comment by mike-thompson-day8** [comment]
@glittershark  In the absence of further information, I'm going to close.  If you end up providing more information we can reopen.
