### ISSUE TITLE
Enforce reg-sub :<- syntax

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame#326]
Currently a `reg-sub` can have any keyword instead of `:<-` to indicate input signals. For example:

```cljs
(re-frame/reg-sub
  :app/second-sub
  :-> [:app/my-cool-sub]
  (fn
    [cool _]
    cool))
```

is perfectly valid. We should enforce `:<-` so that we have the option to use the syntax in the future.

**Comment by mike-thompson-day8** [comment]
@danielcompton  I believe we can close this?

**Comment by danielcompton** [comment]
Yep
