### ISSUE TITLE
Chained Reactions Macro

### ISSUE THREAD

**Issue by dhruvp** [Day8/re-frame#33]
Hey Mike, just wanted to get your thoughts on a macro I thought might be useful before making a PR. The idea is that it's going to be a common operation to have a chained list of reactions that each depend on eachother and it would be useful to have a macro to encapsulate this idea. For example, say app-db is {:a {:b {:c 1}}}. A likely subscription might be 

```
(let [a-reaction (reaction (:a @app-db))
      b-reaction (reaction (:b @a-reaction))
      c-reaction (reaction (:c @b-reaction))]
      (do-something-with c-reaction))
```

In this case the reactions all used simple key functions but you may want a chain of reactions that has more interesting functions. Either way, I wrote a macro that can be used as follows to do the above:

```
(with-chained-reaction [c-reaction [:a :b :c] app-db]
      (do-something-with c-reaction))
```

You pass in a vector with the name of the final ratom, a set of functions to be used in sequence, and your app-db along with any code you want to execute in that context.

The relevant code is here:

```
(defn create-let-bindings
  [previous-ratom functions]
  (if-let [function (first functions)]
    (let [new-ratom (gensym)
          previous-ratom-application `@~previous-ratom
          first-let-binding [new-ratom (list 'reaction (list function previous-ratom-application))]]
      (if (fnext functions)
        (concat first-let-binding
                  (create-let-bindings new-ratom (rest functions)))
        first-let-binding))
    ()))

(defmacro with-chained-reaction
  [[result functions db] & rest]
  (let [let-bindings (into [] (create-let-bindings db functions))]
    `(let ~let-bindings
       (let [~result (get ~let-bindings (- (count ~let-bindings) 2))]
         ~@rest))))
```

Is this something you might be interested in?

**Comment by mike-thompson-day8** [comment]
Hold off for the moment.

There will be a re-vamp of subscriptions in v0.3.0 which make chaining easier, no macros necessary.  Within a few days, I hope.

**Comment by dhruvp** [comment]
Ok sounds good. Thanks!
