### ISSUE TITLE
Error during booting example todo project with "lein figwheel"

### ISSUE THREAD

**Issue by DredderGun** [Day8/re-frame#334]
Hi everyone!
I learn re-frame and i tried to boot example todomvc project from Day8/re-frame repository. 
I typed:
```
cd /re-frame/examples/todomvc
lein figwheel
```
Project has started successfully. But when i change files content, that changes don`t display! For example I changed header in views.cljs file at line 89 `[:h1 "todos. Changed header"]`. And nothing change! I tried reboot figwheel, tried `lein do clean, figwheel`. Nothing help.

At browser console I see that error: `Error: spec check failed: val: {:showing :all} fails spec: todomvc.db/db predicate: [(contains? % :todos)]` But I have no idea how to solve that problem.

Did anyone have the same problem? Can you help me please

**Comment by DredderGun** [comment]
I'm sorry to trouble you. Problem was solved by typing lein command in right way 
```
lein clean
lein figwheel
```

**Comment by mike-thompson-day8** [comment]
@DredderGun glad you found the problem.  Best to ask support questions in the clojurians slack channel for re-frame available here http://clojurians.net/
