### ISSUE TITLE
Citation guidelines

### ISSUE THREAD

**Issue by yochannah** [Day8/re-frame#346]
It would be nice to have guidelines for citing re-frame in academic papers and conference abstracts, for scenarios where acadamic / open source software uses re-frame as part of its stack. Would it be possible to add a CITATION file to the root of the repo for this purpose?

See http://mr-c.github.io/shouldacite/how-to-get-cited.html for guidelines.

**Comment by stumitchell** [comment]
working on it https://github.com/Day8/re-frame/pull/349

**Comment by mike-thompson-day8** [comment]
Fixed in release [0.9.4](https://github.com/Day8/re-frame/blob/master/CHANGES.md#094-20170601)

**Comment by stumitchell** [comment]
@yochannah does this latest release do what you like?

https://github.com/Day8/re-frame/blob/master/CITATION.md

**Comment by yochannah** [comment]
That's brilliant!
