### ISSUE TITLE
Simpler syntax for reg-sub

### ISSUE THREAD

**Issue by mbertheau** [Day8/re-frame#354]
I've been using a macro that allows me to write subscriptions like this:
```clj
(r-sub :result [] [output [:get-in [:output]]
                   words [:get-in [:words]]
                   hanja [:get-in [:hanja]]]
       (query-result words hanja output))
```
Arguments are:
1. subscription keyword
2. vector of direct subscription arguments, equivalent to `fn` argument vector
3. vector of input subscriptions, syntax equivalent to `let`, direct subscription arguments can be used
4. computation body

Here's the macro output for the above example:

```clj
(re-frame.core/reg-sub
  :result
  (fn [[_] _] [(re-frame.core/subscribe [:get-in [:output]])
               (re-frame.core/subscribe [:get-in [:words]])
               (re-frame.core/subscribe [:get-in [:hanja]])])
  (fn [[output words hanja] [_] _] (query-result words hanja output)))
```

Here's another example:
```clj
(r-sub :char-result-group [i] [char-results [:char-results]]
       (get char-results i))

; macro output
(re-frame.core/reg-sub
  :char-result-group
  (fn [[_ i] _] [(re-frame.core/subscribe [:char-results])])
  (fn [[char-results] [_ i] _] (get char-results i)))
```

You can also use the direct subscription arguments as arguments to subscription inputs, something that is afaik not possible with the sugared syntax of `reg-sub`:

```clj
(r-sub :num-char-results-in-group [i] [char-result-group [:char-result-group i]]
       (count char-result-group))

; macro output
(re-frame.core/reg-sub
  :num-char-results-in-group
  (fn [[_ i] _] [(re-frame.core/subscribe [:char-result-group i])])
  (fn [[char-result-group] [_ i] _] (count char-result-group)))
```

If you need access to the whole `app-db`, leave the input subscriptions vector empty and access `db`:
```clj
(r-sub :get-in [path] []
       (get-in db path))

; macro output
(re-frame.core/reg-sub :get-in (fn [db [_ path] _] (get-in db path)))
```

I find this syntax much less alien than `reg-sub`. It also looks and works a lot like `fn` / `let`, which most users will be familiar with.

Here's the macro:
```clj
(defmacro r-sub
  [sub-name args inputs body]
  (let [query-v (into ['_] args)
        partitioned-inputs (partition 2 inputs)
        input-query-vectors (mapv second partitioned-inputs)
        input-names* (mapv first partitioned-inputs)
        input-names (if (empty? input-names*) 'db input-names*)
        input-fn (list 'fn [query-v '_]
                    (mapv #(list 're-frame.core/subscribe %)
                           input-query-vectors))
        value-fn (list 'fn [input-names query-v '_]
                    body)]
    (if (empty? input-query-vectors)
      (list 're-frame.core/reg-sub
        sub-name
        value-fn)
      (list 're-frame.core/reg-sub
        sub-name
        input-fn
        value-fn))))
```

What do you think?

One concern might be that you can't plug in a pure function in stead of the body. I'm still thinking whether there's a valid use case for something like this:
```clj
(r-sub :foo [a b] [c [:c] d [:d a]] some-function)
```

With the above macro this subscription would just return whatever some-function evaluates to. However, the syntax could be extended such that if the body is not a list but a symbol, it's treated as a function, and the subscription effectively calls this function with all arguments as specified to calculate the subscription value. Here's an adapted macro that does that and the macro output for the above example:

```clj
(defmacro r-sub
  [sub-name args inputs body]
  (let [query-v (into ['_] args)
        partitioned-inputs (partition 2 inputs)
        input-query-vectors (mapv second partitioned-inputs)
        input-names* (mapv first partitioned-inputs)
        input-names (if (empty? input-names*) 'db input-names*)
        input-fn (list 'fn [query-v '_]
                    (mapv #(list 're-frame.core/subscribe %)
                           input-query-vectors))
        body* (if (list? body)
                body
                (concat (list body) args input-names*))
        value-fn (list 'fn [input-names query-v '_]
                       body*)]
    (if (empty? input-query-vectors)
      (list 're-frame.core/reg-sub
        sub-name
        value-fn)
      (list 're-frame.core/reg-sub
        sub-name
        input-fn
        value-fn))))

; macro output for the above example
(re-frame.core/reg-sub
  :foo
  (fn [[_ a b] _] [(re-frame.core/subscribe [:c])
                   (re-frame.core/subscribe [:d a])])
  (fn [[c d] [_ a b] _] (some-function a b c d)))
```

**Comment by danielcompton** [comment]
Hi @mbertheau this definitely looks interesting. Would you be able to update your post to show the equivalent `reg-sub` that would be written (where it is possible) so we can compare and contrast?

> One concern might be that you can't plug in a pure function in stead of the body. I'm still thinking whether there's a valid use case for something like this:

Yep, people have cases where we want to unit test a function, so we need to be able to separate it from the `reg-sub`.

**Comment by mbertheau** [comment]
@danielcompton Thanks for your feedback. I updated the post as you suggested.

Re: passing a function instead of a body to the macro: I added a version of the macro that supports that, however I think that actually subscribing and testing subscription results as demonstrated in https://github.com/Day8/re-frame-test would neatly cover unit testing.

**Comment by mike-thompson-day8** [comment]
@mbertheau  thanks for this suggestion. 

What you propose is a fairly thin layer over the top of `reg-sub`.  And, in the process it does introduce the cost of a further micro DSL.

As a result, I'm not sure I can see the cost/benefit working.  I've actively resisted all macros to this point. 

So I'm inclined to not include this in core re-frame.   But please don't be put off trying to help.  I appreciate the effort.

**Comment by mbertheau** [comment]
@mike-thompson-day8 Of course, no problem. Nothing stops me from using re-sub in my own projects :)

Could you elaborate a bit on the cost of a further micro DSL?

**Comment by mike-thompson-day8** [comment]
Every macro introduces a DSL.   To program it, you have to understand the syntax and associated symantecs involved in the macro.  Because it doesn't follow normal clojure rules, you can't understand it without docs.  

So that's a cost you have to weight against the benefits the DSL/macro brings.

**Comment by mbertheau** [comment]
Ok, good to know I didn't miss any of the cost aspects. For me the cost/benefit works out well, but for re-frame that's not my call obviously :-)
