### ISSUE TITLE
Redispatch hangs the browser

### ISSUE THREAD

**Issue by lsenta** [Day8/re-frame#382]
Hi there, thanks for maintaining this repository, it's always a pleasure to work with re-frame & cljs.

This piece of documentation seems incorrect:
https://github.com/Day8/re-frame/blob/master/docs/Solve-the-CPU-hog-problem.md#why-does-a-redispatch-work
(It should be possible to dispatch an event from another one)

In the case of a [simple infinite loop](https://github.com/lsenta/awkward-majine/blob/ba1cc6984673ca63f32e07352d6f5d29313ffaa9/src/cljs/akward_majine/events.cljs#L74-L78),
I'd expect 100% CPU usage AND the browser to be responsive. This is not the case: the browser / tab / console will hang until I kill it from the task manager.

Using a `setTimeout` solves the issue in [this code](https://github.com/lsenta/awkward-majine/blob/ba1cc6984673ca63f32e07352d6f5d29313ffaa9/src/cljs/akward_majine/events.cljs#L47-L54).

Demo repo:
- https://github.com/lsenta/awkward-majine/tree/ba1cc6984673ca63f32e07352d6f5d29313ffaa9 
- `lein figwheel`.
- `test LOOP` button will hang the tab / `Authorize mic` will work

**Comment by danielcompton** [comment]
I haven't had a chance to fully digest this, but it looks like you're not using `^:flush-dom`?. If you read later on in the [CPU hog docs](https://github.com/Day8/re-frame/blob/master/docs/Solve-the-CPU-hog-problem.md#why-does-a-redispatch-work) you'll find an explanation of why this is necessary. Sorry if that's not the issue and we can take a deeper look, but at a glance that seems to be the problem?

**Comment by mike-thompson-day8** [comment]
For the record, here's the docs on what should happen:
https://github.com/Day8/re-frame/blob/master/src/re_frame/router.cljc#L8-L61

**Comment by lsenta** [comment]
@mike-thompson-day8 that's Double Buffering,
From the doc, we could have a simple `tic | flush | toc | flush | tic` approach.
Two queues of events: one is being processed, the other is the destination of `dispatch`. They'd switch role when needed. No need for an FSM.

@danielcompton `:flush-dom` is useful if you want to FORCE a flush before processing an event. Say you have a 2 min events coming, you want to give the browser a chance to clear all animations before.
In my case, I have thousands of 1ms events, by the doc, reframe should already give the control to the browser.

**Comment by lsenta** [comment]
I'd be happy to jump into the internals and provide a PR if it can make re-frame simpler.

**Comment by danielcompton** [comment]
See https://github.com/binaryage/cljs-devtools/issues/20#issuecomment-257399432 and https://github.com/Day8/re-frame/commit/d49965e920b78c61a2baa2d1ef645dd884e372a4. I think this might be what is happening? Can you try removing devtools and see if this still happens?

**Comment by danielcompton** [comment]
@lsenta did this resolve your issue?

**Comment by lsenta** [comment]
@danielcompton 
thanks for sharing this, there's a small difference:
- with devtools: the button is never released, it goes into highlighted state and the browser hangs,
- without devtools: the animation completes

But the browser still hangs & the console goes unresponsive in both cases.

**Comment by mike-thompson-day8** [comment]
Okay, I'm back to this issue after a long absence, sorry.  When re-reading, it seems as if this issue is essentially @lsenta proposing:  
> It should be possible to dispatch an event from another one

It is a core assumption in re-frame that only one event at a time is handled. It makes everything every easy to reason about. That isn't going to change.  It is a mistake to think of events like "function calls" where one can call another. 

Closing.

**Comment by lsenta** [comment]
https://github.com/Day8/re-frame/blob/master/docs/Solve-the-CPU-hog-problem.md#the-re-frame-solution

> Third, within our handler, after it completes one unit (chunk) of work, it should not continue straight on with the next. **Instead, it should do a dispatch to itself** and, in the event vector, include something like the following.

The issue I described is that when I follow this the browser hangs. 

Which means that
https://github.com/Day8/re-frame/blob/master/docs/Solve-the-CPU-hog-problem.md#why-does-a-redispatch-work

> And here's the key: **After handling current events, re-frame yields control to the browser, allowing it to render any pending DOM changes, etc.** After it is finished, the browser will hand control back to the re-frame router loop, which will then handle any other queued events which, in our case, would include the event we just dispatched to perform the next chunk of work.

breaks when events are dispatched "too frequently".

I'm not using re-frame these days, so this is a non-issue for me now,
but I was following the guide and that's probably the symptom of an underlying bug.
