### ISSUE TITLE
`re-frame.core/clear-subscription-cache!` doesn't work on the JVM

### ISSUE THREAD

**Issue by julienfantin** [Day8/re-frame#385]
The implementation of `clear-subscription-cache!` disposes of all the reactions in the cache, but  implicitly relies on the reactions' `on-dispose` hook to clear the map. 

Since on the jvm `dispose!` is a no-oop, that makes `clear-subscription-cache!` a no-op too.

**Comment by julienfantin** [comment]
As an aside this can't be tested right now since the test suite only runs in ClojureScript. Is there any interest in converting the test suite to cljc, and if so should we do that before fixing that issue?

**Comment by danielcompton** [comment]
Running re-frame on the JVM isn't something we do at the moment at Day8. However I'd be happy to look at a PR for converting the tests to CLJC, it would be best if it doesn't significantly add complication to running/writing CLJS tests. I'd also be open to a second PR to `interop.clj` which collects the `on-dispose` functions it gets given, and calls them when they are disposed.
