### ISSUE TITLE
Input loses caret position when typing, if event is delegated to form

### ISSUE THREAD

**Issue by chrisdavies** [Day8/re-frame#399]
In React + JS, I tend to not put "onChange" handlers on all of my inputs (it gets tedious). Instead, I put them on my form:

But in re-frame, this causes the caret to move to the end of any input being typed into:

This doesn't work:

```cljs
[:form {:on-change #(rf/dispatch-sync [:field-change (-> % .-target .-name keyword) (-> % .-target .-value)])}
  [:div.field-group
    [:label.field-label "Name"]
    [:input.field {:value name
                          :name "name"
                          :placeholder "Name"}]]
```

This does work:

```cljs
[:input.field {:value name
                      :on-change #(rf/dispatch-sync [:field-change (-> % .-target .-name keyword) (-> % .-target .-value)])
                      :name "name"
                      :placeholder "Name"}]]
```

Is it simply not possible to do this using event delegation?

Edit: not sure why GitHub is screwing up the formatting in those examples... sorry about that!

Thanks! (re-frame rocks, by the way)

**Comment by chrisdavies** [comment]
Er. I should note that it's much less tedious in re-frame than in React to put an on-change on each input, since re-frame's architecture doesn't require me to create/bind a function within my render, so worst-case workaround, I can do something like this:

```cljs

(defn- sync-field [e]
  (rf/dispatch-sync [:field-change (-> e .-target .-name keyword) (-> e .-target .-value)]))

(defn main-panel []
  (let [name @(rf/subscribe [:name])
        email @(rf/subscribe [:email])]
    [:div.card
      [:header.card-header
        [:h1.card-title (str "Name: " name)]
        [:span.card-subtitle email]]
      [:form
        [:div.field-group
          [:label.field-label "Name"]
          [:input.field {:value name
                         :name "name"
                         :on-change sync-field
                         :placeholder "Name"}]]
        [:div.field-group
          [:label.field-label "Email"]
          [:input.field {:value email
                         :name "email"
                         :on-change sync-field
                         :placeholder "Email"}]]]]))

```

**Comment by mike-thompson-day8** [comment]
A few notes:
1.  This issue should really go against the reagent repo. It isn't a re-frame specific. 
2.  But I wouldn't bother raising that issue because I doubt very much you'll get a fix.  I happen to know something about this area because I provided https://github.com/reagent-project/reagent/pull/126
