### ISSUE TITLE
Access to `app-db` in 2nd and 3rd forms of reg-sub ?

### ISSUE THREAD

**Issue by YurySolovyov** [Day8/re-frame#411]
I was trying to build a set of essentially "computed properties" with 2nd and 3rd forms of `reg-sub`, but at the same time, only having these inputs is not enough, I still need `app-db` most of the time.

Does it make sense to somehow allow accessing `app-db` 2nd and 3rd forms ?

**Comment by mike-thompson-day8** [comment]
Just a reminder that Github issues are not for support.  
https://github.com/Day8/re-frame/blob/master/CONTRIBUTING.md#support-questions

It is probably a poor idea for two reasons:
  1.  anything that subscribes to all of db will rerun every time db changes in any way whatsoever
  2.  Are you sure you really want access to all of db?  It is more likely you'll want access to **part** of `app-db` in which case just subscribe to that part via the right Layer 2 . 

But, it is easy to do ... 
```
(reg-sub  
   :db  
   (fn [db _] 
     db))
```
Now `(subscribe [:db])` reactively returns all of db
