### ISSUE TITLE
Example tests

### ISSUE THREAD

**Issue by gonzaloserrano** [Day8/re-frame#415]
Hi,

I'm new to the Clojure ecosystem and I'm trying to grasp re-frame.

Ideally, I'd like to play with the examples and its tests, but the latter are missed.

Can anyone point me to an idiomatic way to do it?

Thanks.

**Comment by danielcompton** [comment]
HI @gonzaloserrano, welcome to Clojure!

The GitHub issues for re-frame are for bug reports and feature requests. Support requests and usage questions should go to the #re-frame [Clojure Slack channel](http://clojurians.net/), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).

> Ideally, I'd like to play with the examples and its tests, but the latter are missed.

The re-frame tests are at https://github.com/Day8/re-frame/tree/master/test/re_frame.

> Can anyone point me to an idiomatic way to do it?

I'm not sure what "it" refers to here sorry. There's some good examples [here](https://github.com/Day8/re-frame/tree/master/examples), and a list of [external resources](https://github.com/Day8/re-frame/blob/master/docs/External-Resources.md) which has a bunch more good stuff to learn from. Feel free to jump in #re-frame on Clojurians Slack if you have any questions. Thanks!
