### ISSUE TITLE
Put in checks for  dispatch-sync

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#42]
`dispatch-sync` can't be called from within an event handler - only an async `dispatch` can be "called". 

Warn if this is ever attempted. 

Why is it a problem?  Well the the first event handler is given a snapshot of the db as a parameter.  And whatever this first event handler returns will be put back into app-db when it finishes.  So any changes made by an intermediate call to `dispatch-sync`  will be lost.

So the problem sequence would be:
   1.  first event handler called with db snapshot
   2.  dispatch-sync called, making changes to app-db 
   3.  first event handler finishes, and its returned db is written into app-db 

Ie. the changes in step 2 are lost. (no longer in app-db)

**Comment by whodidthis** [comment]
I think some variation of `dispatch-sync` would be handy for controlled inputs, though, as regular `dispatch` is unusable there #39. Just that it would need to use `swap! app-db assoc path` to not overwrite async dispatch queue's results. 

Just an idea and maybe not 0.3 stuff but anyways

**Comment by mike-thompson-day8** [comment]
FAQ entry added:
https://github.com/Day8/re-frame/wiki/FAQ#3-why-cant-i-call-dispatch-sync-in-an-event-handler

**Comment by mike-thompson-day8** [comment]
New error added.  Will be a part of v0.3.2
