### ISSUE TITLE
TodoMVC example not in compliance with official spec

### ISSUE THREAD

**Issue by kennytilton** [Day8/re-frame#420]
Not sure if compliance with the [official TodoMVC spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md), but if so two requirements seem to have been missed: 

"When there are no todos, #main and #footer should be hidden." The example hides only #main.

When editing an existing to-do: "If it's empty the todo should instead be destroyed." The example incidentally replicates the behavior of the Reagent example, re-using the save logic from the new input, which does nothing on a blank input.

**Comment by mike-thompson-day8** [comment]
I'm assuming that https://github.com/Day8/re-frame/pull/434 fixes this issue, and that PR was just merged. So I'm closing.
