### ISSUE TITLE
dispatch-sync errors, even when called from an effect handler

### ISSUE THREAD

**Issue by bendlas** [Day8/re-frame#444]
This should be a valid pattern:

```
(re-frame/reg-fx
  :fx-1
  (fn [_] (re-frame/dispatch-sync [:ev-1])))
```
but with re-frame `0.10.3-rc2`, it gives me

`You can't call dispatch-sync within an event handler.`

ref https://github.com/Day8/re-frame/issues/42

**Comment by danielcompton** [comment]
Is this a new error in that version of re-frame, or has it existed in the past? I'm still waking up from my coffee, but I'm not sure why that would be a valid pattern? An fx is always going to be run in the context of an event being handled, so `dispatch-sync` isn't safe there.

**Comment by bendlas** [comment]
I just ran into it and haven't tested it on older versions. I presume it has been an error case before.
The reason I'd consider it a valid pattern derives from the documentation (https://github.com/Day8/re-frame/wiki/FAQ#2-why-cant-i-call-dispatch-sync-in-an-event-handler). The reason it gives is, that the database updates from the event handler, would override the ones from `dispatch-sync`. 

`reg-fx` doesn't have that problem: It's for capturing the side-effect "off-shoots" from the event loop, after database updates have already been applied (I think, and even if they haven't, `dispatch-sync` from an effect handler could be run against the intermediate db). So one could reasonably expect for effects to be able to run `dispatch-sync`.

Does that make sense?

**Comment by bendlas** [comment]
OK, i see. The issue is, that this would require ordering the `:db` effect before other effects, which isn't something that `re-frame` does, right?

FWIW, for my use case, `(js/setTimeout #(re-frame/dispatch-sync ...))` works, because I just need it to break a `.pushState` loop. I'll leave it to you, whether this should be supported by `re-frame`.

**Comment by danielcompton** [comment]
Thanks, will probably close it for now, btw there is also `^:flush-dom` metadata you can attach to your event which may be helpful.
