### ISSUE TITLE
Suggestion: :dispatch-later should filter out nils like :dispatch-n

### ISSUE THREAD

**Issue by Dexterminator** [Day8/re-frame#455]
The api:s of these two built-in fx handlers are quite similar, but `:dispatch-later` lacks the nil filtering convenience.

**Comment by mike-thompson-day8** [comment]
`dispatch-n` does filter for `nil`
https://github.com/Day8/re-frame/commit/6efdae438f393f8121a2d6dfbf76db00e6dafbf5

That was introduced as a part of the `0.10.0` release.

**Comment by mike-thompson-day8** [comment]
Will be a part of the next release
