### ISSUE TITLE
Docstrings not available for some re-frame.core functions

### ISSUE THREAD

**Issue by rads** [day8/re-frame#456]
The `re-frame.core` namespace includes this comment:
```clojure
;; So, we promote a `defn` in a deeper namespace "up" to the API
;; via a `def` in this namespace.
;;
;; Turns out, this approach makes it hard:
;;   - to auto-generate API docs
;;   - for IDEs to provide code completion on functions in the API
```
As a Cursive user I see that the docstring is parsed using static analysis on the Clojure code. This means there's no way to copy the docstring from another function without changing how Cursive currently works.

This forces libraries to make a decision: do we put the docstring on the _inner_ function or the _outer_ one? Re-frame currently keeps the docstring on the _inner_ function. Unfortunately that results in a developer experience like this:

<img width="607" alt="monosnap 2018-03-06 19-10-45" src="https://user-images.githubusercontent.com/11401/37071598-15f15a62-2172-11e8-83f4-7d45a51d4652.png">

This is confusing and inconvenient for the most common use case. I suggest that we move the docstring to the _outer_ function to allow the docstring to show up as it should:

<img width="607" alt="monosnap 2018-03-06 19-18-54" src="https://user-images.githubusercontent.com/11401/37071824-4b0c7a82-2173-11e8-8e2a-f2ee78516ef8.png">

We can replace the docstring of the _inner_ function with instructions to find the canonical docstring:

<img width="607" alt="monosnap 2018-03-06 19-16-01" src="https://user-images.githubusercontent.com/11401/37071733-d16373ca-2172-11e8-8abf-8893b4a2afd3.png">

I work with many people who are just getting started with Re-frame. For beginners the docstrings are a vital part of the development experience. In exchange for a little internal ugliness we can optimize for the most common use case and improve the usability of the library for everyone.

**Comment by danielcompton** [comment]
See also https://github.com/Day8/re-frame/pull/257 and https://github.com/cursive-ide/cursive/issues/1073.

**Comment by cursive-ide** [comment]
The relevant Cursive issue is cursive-ide/cursive#944. I'll see if I can address this on the Cursive side soon, since this is a common issue with several popular libraries.

**Comment by superstructor** [comment]
Duplicate of #216. Both are now fixed. See comment in that issue.
