### ISSUE TITLE
Upgrade to latest Clojurescript release

### ISSUE THREAD

**Issue by tirkarthi** [Day8/re-frame#463]
Latest Clojurescript release [1.10](https://clojurescript.org/news/2018-03-26-release) fixes JDK 9 compatibility issue. Relevant JIRA issue : https://dev.clojure.org/jira/browse/CLJS-2377

**Comment by danielcompton** [comment]
@tirkarthi the version of ClojureScript that you include on your project will override whatever version of ClojureScript we have in re-frame's dependencies, so you only need to upgrade your own version of CLJS. The version we use for re-frame is a lower bound that re-frame requires, so it's going to be a long time before we require 1.10. Thanks for the note though!
