### ISSUE TITLE
Docs missing a statechart guide

### ISSUE THREAD

**Issue by OliverM** [Day8/re-frame#47]
I'm a refugee of big javascript MVC frameworks ([Sproutcore](https://github.com/sproutcore/sproutcore) in my case). But one thing I loved about SproutCore was how it made statecharts a first-class interaction model. Entering states registered appropriate event handlers (click, etc), provided nesting, concurrent execution & history states, essentially everything you'd like to see in a mature statechart library. What's the clojurescript equivalent, if any? Could any pointers be included in the guide? I see you referenced [Automat](https://github.com/ztellman/automat) previously, but it seems to be at a FSM level, not a hierarchical state machine level. [Stativus](https://github.com/etgryphon/stativus) pulls the SproutCore statechart framework out into a stand-alone library though I've not used it. Is it too early for any concrete recommendations?

**Comment by mike-thompson-day8** [comment]
I'm not aware of an equivalent. But it is certainly an interesting area.  I tried looking at Stativus but its not very well documented. 

I'd be quite happy to see ideas/thoughts/approaches put into a Wiki page. Let let the ideas mature there.  Or in this ticket.

**Comment by vladar** [comment]
Some other existing tools (js):

https://github.com/DavidDurman/statechart
https://github.com/jbeard4/SCION-CORE

**Comment by jhund** [comment]
There is https://github.com/nodename/stately (cljs statechart lib, currently using parts of re-frame).

**Comment by mike-thompson-day8** [comment]
Here's a high quality video on stately:
https://www.youtube.com/watch?v=klqorRUPluw

**Comment by mike-thompson-day8** [comment]
Closing.  I've put links to Stately into the External Resources doc (now in `develop`).
