### ISSUE TITLE
nested async call in an effect handler

### ISSUE THREAD

**Issue by jiacai2050** [Day8/re-frame#476]
According to [Talking-To-Servers](https://github.com/Day8/re-frame/blob/master/docs/Talking-To-Servers.md), I define an effect handler to deal with side-effect, but in this fx, I need to call two async call, something like

```clojure

(rf/reg-fx
 :chrome-query
 (fn [[start end text]]
   (js/chrome.history.search (clj->js {:text (or text "")
                                       :startTime start
                                       :endTime end
                                       :maxResults 1000})
                             (fn [items]
                               (mapv #(js/chrome.history.getVisits (clj->js {:url (.-url %)})
                                                                  (fn [visits]
                                                                    (rf/dispatch [:query-result visits])))
                                    items)))))
```

For every item returned from `search`, I need to call `getVisits` to get details. 
My question here is how to accumulate those results into `app-db`.
Thanks in advanced.

**Comment by mike-thompson-day8** [comment]
I'm afraid I don't understand the question.  But it does not seem as if you are reporting an issue or noting possible improvements which is the purpose of github issues.  Please ask usage/tutorial questions via the #re-frame channel in http://clojurians.net/
