### ISSUE TITLE
Is there anything wrong with subscriptions that subscribe to other subscriptions?

### ISSUE THREAD

**Issue by rsslldnphy** [Day8/re-frame#48]
I know you shouldn't but subscriptions in handlers, and what to do instead. However, is the same true for putting subscriptions inside subscriptions? Here's a simplified example use case (assume that the intermediate stages represented by the different subscriptions are required by different parts of the view, such as a label showing the current filter, a set of pagination link etc):

```clojure
(register-sub
  :data
  (fn [db _] (reaction (:data @db))))

(register-sub
  :sort-order
  (fn [db _] (reaction (:sort-order @db))))

(register-sub
  :filter
  (fn [db _] (reaction (:filter @db))))

(register-sub
  :table-data
  (fn [db _] (let [data        (reaction @(subscribe [:data]))
                   type-filter (reaction @(subscribe [:filter]))
                   sort-order  (reaction @(subscribe [:sort-order]))]
    (reaction (sort-by @sort-order (filter #(= (:type %) @filter) @data)))))

(register-sub
  :table-data-page
  (fn [db _] (let [table-data (reaction @(subscribe [:table-data]))]
    (reaction (take 10 @table-data))))
  ```

My gut feeling was that it should be ok to have subscriptions subscribe to other subscriptions in this way, as it's akin to chaining reactions - however the way I'm doing it at the moment definitely looks like a bit of a hack.

**Comment by mike-thompson-day8** [comment]
It is fine for subscriptions handlers can use other subscriptions. 

But easier to write it this way ... 

```clojure
(register-sub
  :table-data
  (fn [db _] (let [data          (subscribe [:data])
                   type-filter   (subscribe [:filter])
                   sort-order    (subscribe [:sort-order])]
    (reaction (sort-by @sort-order (filter #(= (:type %) @filter) @data)))))

(register-sub
  :table-data-page
  (fn [db _] 
    (let [table-data (subscribe [:table-data])]
    (reaction (take 10 @table-data))))
  ```

**Comment by mike-thompson-day8** [comment]
This has come up a couple of times, so I've added an FAQ entry:
https://github.com/Day8/re-frame/wiki/FAQ#2-subscriptions-in-a-subscription-handler

**Comment by rsslldnphy** [comment]
Ah, thanks! I'm sure I wrapped the subscribe in a new reaction because I was having trouble using the subscription directly, but it seems to work fine now, so I must have been doing something else wrong.
