### ISSUE TITLE
Handle metadata in subscription vectors

### ISSUE THREAD

**Issue by p-himik** [Day8/re-frame#500]
I have a subscription `:q` that just queries some data from `(:data db)` in a kinda relational DB manner.
So, a subscription like `[:q :child {:parent 7}]` returns a map of child-id->child of all children that have `:parent` set to 7.
Most of the time I want just a list of children, so I added `:flat` metadata - now `[:q :child ^:flat {:parent 7}]` returns a list of children in no particular order.

Quite a bit late I discovered an issue with this approach - it doesn't work well with the current implementation of the subscription caching.
So, if the former sub is executed first, the latter will then return a map instead of a list.

I don't know whether you want to take the metadata into account when caching subs, but at the very least it's probably worth mentioning in the documentation that metadata doesn't work.

**Comment by p-himik** [comment]
Just checked the implementation - yeah, taking metadata into account for sub caching doesn't appear to be feasible because it can be arbitrarily nested.

**Comment by danielcompton** [comment]
Yeah I don't know that this is going to be easy to do. I guess I'd suggest adding the `:flat` explicitly as a subscription parameter. Will close this for now, but happy to reopen if more info comes to light.

**Comment by andrewzhurov** [comment]
From Clojure perspective "metadata does not impact equality"
According to this reference: https://clojure.org/reference/metadata
