### ISSUE TITLE
Feature: let (dispatch ...) take multiple args

### ISSUE THREAD

**Issue by jamieorc** [Day8/re-frame#51]
Sometimes I want to dispatch more than one handler at a time. Seems like it would be rather trivial to modify `dispatch` to take an indefinitely number of args and then dispatch each one. Something like

```clojure
(defn dispatch [&event-vs]
  (doseq [event-v event-vs]
    (if (nil? event-v)
      (warn "re-frame: \"dispatch\" is ignoring a nil event.")     ;; nil would close the channel
      (put! event-chan event-v)))
  nil)
```

What do you think?

**Comment by mike-thompson-day8** [comment]
Indeed, it would be simple, which is tempting.  But I'm slightly cautious.  

`core.async/put!`  itself only allows you to put one thing at a time, and there's a reason for that - you want your API to be the simplest thing possible, while still facilitating the more complex things.

**Comment by jamieorc** [comment]
Only one thing is being `put!` at a time, unless I misunderstand something.

**Comment by mike-thompson-day8** [comment]
I'm pointing out that `put!` doesn't support multiple additions in one go.  Instead `put!` provides the minimal API and then lets you build more complicated things on top (eg, multiple puts).  And I'm suggesting that `dispatch` should be minimal in the same way.  

There's a another, more subtle, reason I'm resisting this.  I wonder if one day we'll actually want to add new, optional parameters to `dispatch` after the event.  Additional flags. I wouldn't want to cut off that possibility for the moment.  

So I'm going to say no to this for the moment.  I'm hoping that your use-case can be satisfied by a `dispatch-n` function like this which is a part of your own app:
```
(defn emit-n 
  [& event-vs]
  (doall (map dispatch (remove nil? event-vs)))
  nil)
```

**Comment by jamieorc** [comment]
Actually, the second reason makes a lot more sense to me. If you think the api could change, then you don't want to change it up. Cheers.
