### ISSUE TITLE
Ship with spec validation interceptor

### ISSUE THREAD

**Issue by urzds** [Day8/re-frame#515]
It would be nice if re-frame could bring a few more batteries, like a spec validation interceptor for the application state (i.e. `:db`). It could explain validation errors on the browser JavaScript console, roll back the offending changes, integrate with re-frame-10x, ...

[kee-frame](https://github.com/ingesolvoll/kee-frame/) comes with such an interceptor, but it's focus is on other unrelated, new concepts (controllers).

Something similar was requested in #457, but the main focus of that ticket lies elsewhere.

**Comment by mike-thompson-day8** [comment]
@urzds as @danielcompton says we look forward to officially integrating spec when it becomes stable but without a known timeline for that, I'm going to close this issue for now.

**Comment by urzds** [comment]
What about Plumatic Schema as an alternative?

**Comment by mike-thompson-day8** [comment]
@urzds 
> What about Plumatic Schema as an alternative?

`spec` is the way of the future so we'll embrace that officially in due course.  And, in the time being, you can easily engineer to use either `spec` or `Schema` yourself.
