### ISSUE TITLE
reg-sub, syntax sugar and single values

### ISSUE THREAD

**Issue by urzds** [Day8/re-frame#516]
The [documentation for reg-sub](https://cljdoc.org/d/re-frame/re-frame/0.10.6/api/re-frame.subs#reg-sub) gives an example as follows for the "syntax sugar" case:
```clj
(reg-sub
  ::example
  :<- [::a]
  :<- [::b]
  (fn [[a b] _query]
    {:a a :b b}))
```

As a re-frame user, I would think I could quickly adapt it to my case like this:
```clj
(reg-sub
  ::example
  :<- [::single]
  (fn [[single] _query]
    {:s single}))
```

This will blow up with very hard to understand and debug error messages like `Error rendering component` and `Error: nth not supported on this type function <gibberish>`.

To improve usability without breaking backwards compatibility (the easy fix would be to always pass a vector, even in case there is only one `:<-`), I would suggest to test whether the user-supplied function expects a vector in the first argument or not and pass it the input signal accordingly.

**Comment by mike-thompson-day8** [comment]
@urzds there's no way to check what the computation function is expecting as the first argument.  And a backwards incompatible change is not an option.

**Comment by mike-thompson-day8** [comment]
@urzds just to clear, your suggestion of "the easy fix would be to always pass a vector, even in case there is only one :<-)," would not be backwards compatible because existing code bases have computation functions which expect to get a single value. 

I'm going to close this.  Can't fix.

**Comment by urzds** [comment]
> @urzds just to clear, your suggestion of "the easy fix would be to always pass a vector, even in case there is only one :<-)," would not be backwards compatible because existing code bases have computation functions which expect to get a single value.

That was why I gave the other suggestion "to improve usability without breaking backwards compatibility".

Can we at least specifically mention this case in the description of the `:<-` syntax sugar in the docs? That might help the next guy who tries to derive their code from the syntax sugar example.

**Comment by mike-thompson-day8** [comment]
> Can we at least specifically mention this case in the description of the :<- syntax sugar in the docs? That might help the next guy who tries to derive their code from the syntax sugar example.

Absolutely. Are you able to supply a PR which adds the words you'd like to see in the place you'd prefer to see them?  I'm imagining a `WARNING` section somewhere?  Where would have best caught your eye as a learner?
