### ISSUE TITLE
:dispatch-later not sent in React Native on Android when in background

### ISSUE THREAD

**Issue by Looveh** [Day8/re-frame#526]
Observed when running `re-frame v0.9.4` in React Native on an Android device (tested with multiple Android manufacturers/versions).

Create and register a handler:

```
(reg-event-fx
  :my-evt
  (fn [_ _]
    (println "my-evt triggered")
    {:dispatch-later [{:ms 1000
                       :dispatch [:my-evt]}]})
```

Steps to reproduce:
1. Start app on Android with the above handler registered
2. `(dispatch [:my-evt])`
3. Observe how logs are printed every second
4. Bring app into background
5. Observe how logs stop printing
6. Bring app into foreground
7. Observe how logs resume printing

**Comment by Looveh** [comment]
Note: This is not related to the app being stopped/suspended - if the app is connected to a Bluetooth device it still continues to respond to Bluetooth events.

**Comment by danielcompton** [comment]
@Looveh at Day8 we have no react-native experience at all so are unlikely to be able to help with any deep debugging. However, this sounds like the JS engine just throttling timeouts when the app is in the background. Can you check what happens if you use `js/setTimeout` or `js/setInterval` directly?

**Comment by Looveh** [comment]
@danielcompton Thanks, getting the same behavior when running `js/setTimeout` and `js/setInterval`, if that's what `re-frame` is running under the hood to trigger `:dispatch-later`'s I'll move this issue to React Native and come back here if I ever find a solution (let's hope) :)
