### ISSUE TITLE
Outdated interceptor use in example code?

### ISSUE THREAD

**Issue by AndreaCrotti** [day8/re-frame#527]
In the todomvc example I find code like
```
(defn check-and-throw
  "Throws an exception if `db` doesn't match the Spec `a-spec`."
  [a-spec db]
  (when-not (s/valid? a-spec db)
    (throw (ex-info (str "spec check failed: " (s/explain-str a-spec db)) {}))))

;; now we create an interceptor using `after`
(def check-spec-interceptor (after (partial check-and-throw :todomvc.db/db)))
```

that shows how to use interceptors.
However using that same style actually gives a warning, I guess because that's the deprecated way to define interceptors.
The documentation in fact uses a different style, so I wonder if the example should be simply updated?

The strange thing is that the example is actually newer than the documentation in `Interceptors.md`, at least from a quick `git blame`.

**Comment by cpdean** [comment]
is this the source of this error when trying to filter todo items by their completed status?

![image](https://user-images.githubusercontent.com/160099/53526841-40aac080-3ab3-11e9-9c62-3686a927fd6e.png)

**Comment by danielcompton** [comment]
> However using that same style actually gives a warning, I guess because that's the deprecated way to define interceptors.

I'm not seeing any warnings when running the todomvc project. Can you give a bit more context around what the warning is, and what the change in style is that you're referring to?

**Comment by dawran6** [comment]
@AndreaCrotti do you perhaps refer to the usage of `re-frame.core/after`? It is only briefly mentioned in the [Appendix of Intercepter.md](https://github.com/Day8/re-frame/blob/master/docs/Interceptors.md#appendix), but `after` seems pretty common to me. Perhaps we can improve the documentation to address the usage of common intercepter patterns like using `path` and `after`.

You can find a bit more usage of `after` in the [docstring](https://cljdoc.org/d/re-frame/re-frame/0.10.8/api/re-frame.std-interceptors#after):

```
returns an interceptor which runs a given function `f` in the `:after`
position, presumably for side effects.

`f` is called with two arguments: the `:effects` value for `:db`
(or the `coeffect` value of db if no db effect is returned) and the event.
Its return value is ignored, so `f` can only side-effect.

Examples use can be seen in the /examples/todomvc:
   - `f` runs schema validation (reporting any errors found).
   - `f` writes to localstorage.
```

**Comment by superstructor** [comment]
As noted above, I’m not seeing a warning and I’m not seeing deprecated use of interceptors. Earlier, @danielcompton requested further information/clarification but that hasn’t been supplied. Docs are also improving a lot soon in future changes. 

Closing.
