### ISSUE TITLE
compile error example/simple

### ISSUE THREAD

**Issue by pouya-abbassi** [Day8/re-frame#529]
I've tried to run the "simple" example project, got this error:
https://gist.github.com/pouya-abbassi/266d7ab406d4b5001404dc5ff8b479f4

```bash
─➤  lein version
Leiningen 2.8.3 on Java 10.0.2 OpenJDK 64-Bit Server VM
```
I can create re-frame project and run it already, I just can't run this sample code.

**Comment by danielcompton** [comment]
Thanks for the heads up, I'll update the dependencies to handle Java 9+.
