### ISSUE TITLE
Fix Logging And Error Reporting

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#53]
At the moment, re-frame makes use of various logging functions like  `re-frame.utils/warn`.

But functions in this ns are currently too hard coded and inflexible.  There's been a couple of suggestions around improving that situation:   #43 and #34

But everyone's idea about logging is different. And re-frame is too low level to be opinionated in this area. 

I'm personally not keen on goog's logging but others like it and want to use it. And on IE you can't use `console.group` because it doesn't exist. Etc.

So I propose that re-frame has a bunch of standard reporting functions defined, each with a default implementation, but provides a way for apps to define their own implementation. 

`(re-frame.core/set-logging!  my-warn my-log my-error my-group my-ungroup)`

**Notice that error has been added to the list -- for exceptions.

These alternative implementations can then be as complicated as needed and use goog.logging as required.

**Comment by hura** [comment]
This is def the best possible solution. Let everybody plug in their own loggers and maybe give some recipes (wiki) for common loggers.
Don't have anything to add, just wanted to :+1:

**Comment by mike-thompson-day8** [comment]
https://github.com/Day8/re-frame/wiki/FAQ#3-can-re-frame-use-my-logging-functions

This change will be a part of v0.4.0
