### ISSUE TITLE
Example todomvc has broken filter buttons.

### ISSUE THREAD

**Issue by cpdean** [Day8/re-frame#530]
On master, after fixing the syntax errors to get the lein project to build, the app starts up and seems completely functional except for the errors that get thrown when you click on any of the filters (all, active, completed).

```
core.cljs:316 Uncaught Error: No protocol method IMapEntry.-key defined for type cljs.core/LazySeq: (:filter "all")
    at Object.cljs$core$missing_protocol [as missing_protocol] (core.cljs:316)
    at Object.cljs$core$_key [as _key] (core.cljs:644)
    at Object.cljs$core$key [as key] (core.cljs:8927)
    at merge_entry (core.cljs:9021)
    at core.cljs:2452
    at Function.cljs$core$IFn$_invoke$arity$3 (core.cljs:2452)
    at Object.cljs$core$IReduce$_reduce$arity$3 (core.cljs:3252)
    at Function.cljs$core$IFn$_invoke$arity$3 (core.cljs:2522)
    at core.cljs:9026
    at core.cljs:1509
```

What does this mean and how can we fix this?

![image](https://user-images.githubusercontent.com/160099/53528375-76ea3f00-3ab7-11e9-8c6e-20f1d507c34e.png)

**Comment by danielcompton** [comment]
This should be fixed now. Thanks for the report!

**Comment by cpdean** [comment]
Thank you! Confirmed this works now.

What does the error mean and what's different between those patch versions of secretary so that this works now?

**Comment by danielcompton** [comment]
I know what the error is saying but don't have time to explain fully sorry. The diff is here: https://github.com/clj-commons/secretary/compare/v1.2.3...v1.2.4, I think the key line is https://github.com/clj-commons/secretary/compare/v1.2.3...v1.2.4#diff-eb1b24dd02a2e9851c67cf6406525f90R252.
