### ISSUE TITLE
Using an ordered map should order the effects events by the current imp.

### ISSUE THREAD

**Issue by TristeFigure** [Day8/re-frame#535]
Pardon me if I'm wrong, but having read the documentation & the code ...

> Order Of Effects?
> There isn't one.
> `do-fx` does not currently provide you with control over the order in which side effects occur. The `:db` side effect might happen before `:dispatch`, or not. You can't rely on it.

... it seems using an ordered map would order the effects.

Maybe rewrite the doc to reflect that if I'm right (I did not test my proposition).

**Comment by mike-thompson-day8** [comment]
An event handler may return an ordered map, but interceptors on that event handler, being unaware that they are dealing with an ordered map, might turn it back into a map.
