### ISSUE TITLE
Definitively identifying deref causing a subscription to trigger

### ISSUE THREAD

**Issue by jamesnyika** [Day8/re-frame#540]
Hi
 I am using re-frame with expo/react native and my components are deeply nested .I create a pass into this nested structure a new atom I construct FROM the atom of a subscription. I pass that in since reactions cannot be edited and I want this structure to be edited. However, the nested structure contains a component that displays a modal. Whenever I open the modal and close the modal control, it forces a re-fetch of the subscription data. 

 ## The questions:
  1. Why would the subscription be called again if I did not pass into the nested structure the original reaction ? 

 2. Should I worry about this retrigger even if the data has not changed ? I see it pulling the same stuff but maybe it is just passing back results that are cached ? Are they cached ? 

 3. Is there a way in re-frame to definitively identify which deref of the reaction/atom causes the subscription to be re-run ? 

 thanks for any help on this.

**Comment by danielcompton** [comment]
Hi @jamesnyika, Github issues for re-frame are for bug reports and feature requests. Support requests and usage questions should go to the #re-frame [Clojure Slack channel](http://clojurians.net/), the [ClojureScript mailing list](https://groups.google.com/forum/#!forum/clojurescript), or the [Reagent mailing list](https://groups.google.com/forum/#!forum/reagent-project).

There's not really enough information here to answer your question properly. I'd suggest taking a look at [re-frame-10x](https://github.com/Day8/re-frame-10x) as it has some debugging tools around subscriptions which may help answer this question for you.

To your question "Is there a way in re-frame to definitively identify which deref of the reaction/atom causes the subscription to be re-run ?", at one time I experimented with visualising the dependencies between re-frame's db, subscriptions, and views in re-frame-10x. It got a bit noisy and I never got it good enough to ship, but if you just want to answer that question you could probably get it by digging through the re-frame-10x trace logs and constructing the tree for yourself.

**Comment by jamesnyika** [comment]
Thank you @danielcompton I will follow your advice.

**Comment by jamesnyika** [comment]
For anyone who might look at this issue and wonders what I found out, please read [this section from re-frame-10x](
 https://github.com/Day8/re-frame-10x/blob/master/docs/HyperlinkedInformation/UnchangedLayer2.md)  which describes some of how re-frame handles layer 2 and layer 3 queries. 

It helped me answer my questions as follows : 
Why would the subscription be called again if I did not pass into the nested structure the original reaction ?
    * It would not. Looking carefully at where all the derefs happen will normally pretty clearly identify why you might be having a re-rendering occuring. In my case, I had two bugs: 
      1.  I had a hidden subscription I could not see in one of my components (just sloppiness). So do a simple search for (rf/subscribe ...  to make your life easier
      2. When you define the key metadata for your components, take care if you are using something like a random number generator in there that changes the key on every repaint. It is a dog of a problem. 

Should I worry about this retrigger even if the data has not changed ? I see it pulling the same stuff but maybe it is just passing back results that are cached ? Are they cached ?

    * Layer 2 subscription - which pull directly from app-db are cheap and inexpensive. 
     * Layer 3 subscriptions - that is where you can have a problem. But re-frame checks to see if the inputs have changed and if not, then it does not rerun them. So there is no caching.. but there is no re-running either. 


Is there a way in re-frame to definitively identify which deref of the reaction/atom causes the subscription to be re-run ?

   * not really. Answer is complicated and it depends. You can see it sometimes with 10x and in other cases... takes some digging. But if you solve the above two .. this becomes less relevant in my opinion.
