### ISSUE TITLE
Add docs for :<-

### ISSUE THREAD

**Issue by yochannah** [day8/re-frame#544]
`:<-` seems to possibly be an undocumented feature - it appears here: https://github.com/Day8/re-frame/blob/master/examples/todomvc/src/todomvc/subs.cljs#L127 as part of the todo app example, but I'm not sure where it's documented, if anywhere. 

It's also possible the docs exist but are hard to find, since GitHub and Google don't really like searching for punctuation. Is there some way to mitigate this? I'm guessing possibly not, short of renaming it and breaking backwards compatibility.

**Comment by superstructor** [comment]
This issue has now been addressed in three ways:
- All core functions now have doc strings which appear in the new API documentation. The doc string for `regsub` explains `:<-`. This change will make it easier for programmers to discover and understand this feature. 
- The new re-frame tutorial will have a textual search facility (allowing you to find `:<-` more easily) 
- The part of the tutorial for subscriptions is currently being improved and now discusses this feature directly (will be released soon)

Closing.
