### ISSUE TITLE
Subscription behaviour using a keyword as the computation fn (correct but confusing) -> doc ?

### ISSUE THREAD

**Issue by clepelli** [day8/re-frame#555]
Hi !

First, thanks for the wonderful library !

I have just spotted a confusing behaviour when using simple subscriptions :

(re-frame/reg-sub
  ::test
  :test)

I "abusively" use the keyword :test as a function, and expect subscription to ::test to just retrieve (:test db) when :test key is set in db, or nil. It looks nice and simple for simple cases like this... 
But instead of nil when (:test db) is nil the ::test subscription returns the query-vec : [::test]

This is correct as in (:test db query-vec), query-vec is used as fallback value, but I think it may be a good addition to warn about this in subscription documentation.

Regards,
Clément.

**Comment by smahood** [comment]
I couldn't find this recommended in the long form docs, but it makes total sense to assume it would work based on the docstring.

`reg-sub` tests to see if the first input is a function, and `(fn? :test)` returns false. If we checked for keywords as well then it seems like your usage should work fine. In the meantime, you could use 
`(re-frame/reg-sub ::test #(:test %))` to get the behavior you are looking for.

**Comment by hkjels** [comment]
I think checking for a keyword makes sense. I usually have a utility function that takes care of this, but just using a keyword would be nicer

**Comment by prook** [comment]
> `reg-sub` tests to see if the first input is a function, and `(fn? :test)` returns false. If we checked for keywords as well then it seems like your usage should work fine.

@smahood, with all respect, this is incorrect. That `(fn? f)` check in "[single inputs fn](https://github.com/day8/re-frame/blob/master/src/re_frame/subs.cljc#L342)" case is for input signal, not `computation-fn`. There is no `(fn? computation-fn)` check anywhere in `reg-sub`.

The problem described by OP is that `computation-fn` contract ([subs.cljc#L376](https://github.com/day8/re-frame/blob/master/src/re_frame/subs.cljc#L376)) is `(input-signals, query-vec) -> computed-value`, while [keyword-as-a-function](https://clojure.org/reference/data_structures#Keywords) contract is `(m, default) -> m[k] | default` (pardon the arbitrary notation). This difference makes keywords unsuitable for use as `computation-fn`.

At the same time, keyword-as-fn would be very convenient in extraction subscriptions (as in level 2 in signal graph in `/docs/SubscriptionInfographic.md`), and I wound up here, because I got bitten the same way as OP.

**Comment by mike-thompson-day8** [comment]
I do understand the constant gravitational force of convenience and the good reasons for it often but in this case, the benefit doesn't seem to outweigh the need for special casing. 

I'll leave this ticket open for the moment, more as a future reminder, but I can't see myself making this change.

**Comment by prook** [comment]
Agreed. However, an explaining blurb similar to [this](https://github.com/day8/re-frame/blob/master/docs/SubscriptionsCleanup.md#a-final-faq) would be extremely helpful.

**Comment by prook** [comment]
Agreed. However, an explanation in /docs similar to [this extremely helpful blurb](https://github.com/day8/re-frame/blob/master/docs/SubscriptionsCleanup.md#a-final-faq) could prevent some burns.

**Comment by clepelli** [comment]
I agree too. No need to change the behaviour but a warning in the documentation could be read by framework beginners before they make the mistake.

**Comment by smahood** [comment]
I was digging in to this to better understand how things work (thanks @prook for catching my error) and I think I found the place where a keyword check would go. Not pushing for a change, but I thought it might be interesting in case anyone else was curious how this part of re-frame worked.

It seems like we can add a  `keyword?` check in the 'let' block at [subs.cljc#L376](https://github.com/day8/re-frame/blob/master/src/re_frame/subs.cljc#L376)  

```
(let [computation-fn (if (and (= 0 (count input-args)) 
                              (keyword? computation-fn))
                       #(computation-fn %)
                       computation-fn)
      subscription (computation-fn (deref-input-signals subscriptions query-id) query-vec)])
  (trace/merge-trace! {:tags {:value subscription}})
  subscription)
```
I tested this with one of my existing projects and it seemed to give the desired behavior with nil values and didn't cause any problems with my other subscriptions, but I haven't tested it extensively so it's possible I missed something else.

For anyone looking for the same kind of behavior without having to change re-frame,  https://gitlab.com/nikperic/reframe-utils#reg-basic-sub is another example of wrapping function that you could use.

**Comment by prook** [comment]
That `(= 0 (count input-args))` though... Consider missing `:foo` in the following example:

```clojure
(rf/reg-sub
  :bar-map
  (fn [db]
    (get-in [:wherever :bar-map :is] db))

(rf/reg-sub
  :foo-in-bar
  :<- [:bar-map]
  :foo
```

But we digress...

Special-casing keywords in `reg-sub` is clearly not a step in the right direction, util fns like `reg-basic-sub` are. (I'd argue about the name, `reg-keyword-sub` comes to mind, but whatever. :)

**Comment by superstructor** [comment]
Although @mike-thompson-day8  said he’d leave this ticket open, I’m currently doing some spring cleaning of issues and PRs and this one looks like it has been well answered.

So, I’m now closing.
