### ISSUE TITLE
re-frame examples do not compile due to re-frame version unavailable on clojars

### ISSUE THREAD

**Issue by thomaswilliams77** [day8/re-frame#556]
Error: Could not find artifact re-frame:re-frame:jar:0.11.0-rc2-SNAPSHOT in clojars (https://repo.clojars.org/)

Changed dependency version to "0.11.0-rc1" in project.clj and that fixes it.

**Comment by superstructor** [comment]
Thanks for the bug report @thomaswilliams77 and apologies for the inconvenience.

**Comment by thomaswilliams77** [comment]
No prob, great work on this project. And great examples. Thank you!
