### ISSUE TITLE
Usage Notes

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame#56]
@lorddoig raised the following in #43.  Transferred here for further discussion so as to not overload the original ticket with too many threads of thought ...

---

On another note - I really like re-frame and using it pretty heavily has led to some other thoughts (this is all subjective and sorry to hijack the issue, can open a separate one if you agree with any of the following):
1. In pursuit of readability and "elegance" I find it much better to define a named function and then register it as a handler/subscription later, but this creates non-trivial cognitive load in having to track functions that are or aren't registered and in the fact that I can (even if I arguably shouldn't) allow the keyword event ID to differ from the function name.
2. I habitually use the `trim-v` middleware on almost all handlers, and I frequently get tripped up by the fact that the middleware doesn't apply to subscriptions, 99% of which look like `(defn some-sub [db [_ x]])` so maybe there's a case for extending the middleware concept to those
3. I know middleware has to be declared outside the handler body so re-frame knows what to do with the return value, but this separation of logic seems less than ideal.  It makes sense in the context of e.g. webapp routes because an app typically only has one set of routes so you can be relatively sure that when you find them you'll find where they're wrapped within a few lines 99% of the time.  This isn't true for a multitude of handlers possibly spread across namespaces.
4. Making relatively trivial setters and getters requires 4 forms:
   1. `(defn set-thing [db _])`
   2. `(defn get-thing [db _])`
   3. `(register-handler :set-thing trim-v set-thing)`
   4. `(register-sub :get-thing get-thing)`
   
   Of course these can often be parameterized but that doesn't quite solve everything.

With regard to these points I think there's perhaps a case for making a few macros that covers some of them (e.g. `defhandler`, `defsub`), or doing something akin to [sente](https://github.com/ptaoussanis/sente) for handlers i.e. a multimethod that could look something like

``` clojure
(defmulti handle (fn [_ _ meta] (:id meta)))

(defmethod handle :set-thing
  [db ?data {:keys [id]}]
  (assoc db :thing (do-something ?data))

(re-frame.core/set-handler! handle)
```

Putting all stuff not immediately pertinent to the domain problem in a map as the last arg seems a friendly and extensible solution.  This doesn't play so nice with middleware as it is now, but with regard to point 3 - what if middleware could be applied in the function body with a `wrap` macro that told re-frame what to do in the return value metadata?  Of course this still leaves the subscriptions question open.

Thoughts?  Feel free to call me out on any of this and tell me I'm doing it wrong.

**Comment by rej156** [comment]
While being more true to the ClojureScript way, a multi-method abstraction does feel different to a normal  flux pattern implementation.
There is also the point that you've raised about the handler middleware!

In combination with Sente, it does make sense in my head for a "flux dispatch of a sente multi-method" as the current api suggests!

**Comment by mike-thompson-day8** [comment]
This is a very old issue which I should have closed ages ago.  Closing now. All issues outlined either handled or rejected as won't fix.
