### ISSUE TITLE
Debug log level is missing

### ISSUE THREAD

**Issue by p-himik** [day8/re-frame#561]
`js/console.debug` is a thing: https://developer.mozilla.org/en-US/docs/Web/API/Console/debug
And it's well supported: https://caniuse.com/#feat=mdn-api_console_debug

Alas, it's impossible to add if from a user's side because of an assert on `(contains? @loggers level)`.

**Comment by mike-thompson-day8** [comment]
Can you give more details about what you'd like changed or added?  A PR?
