### ISSUE TITLE
cljdoc is broken

### ISSUE THREAD

**Issue by hkjels** [day8/re-frame#576]
Apparently, there's an exception in the build-process that makes cljdoc fail unfortunately.
https://cljdoc.org/builds/26960

**Comment by martinklepsch** [comment]
This is likely an issue with cljdoc itself. While creating the `cljdoc.edn` configuration system I hardcoded the configuration for some popular projects that I cared about. If you grep for „hardcoded“ in the cljdoc code base this will be easy to find (and fix).

**Comment by mike-thompson-day8** [comment]
Thanks, @martinklepsch and @hkjels.  Will investigate

**Comment by superstructor** [comment]
This was [recently fixed in cljdocs](https://github.com/cljdoc/cljdoc/commit/b8b77475edcd0befdc9ddfc0809fcad6761333c5) by @davidjameshumphreys Thanks 😄 

Closing.
