### ISSUE TITLE
The documentation should talk of 7 dominos, not 6

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-frame#579]
## Summary

  - The introductory re-frame documentation should be changed to better show re-frame's separation of concerns
  - Specifically, there should be 7 re-frame dominos, not 6. 
  - Specifically, the existing domino #2 be split into two dominos

## Notes
 
The following explanatory notes are written from the point of view of the current 6 domino model. These notes might serve as the basis of some of the new documentation. 

A terse formula describing dominos #2 and #3 (combined) is:
```
w' = f(w, e) 
```

Given the current state of the world `w`, and the occurance of an event `e`, the function `f` will compute the next state of the world `w'`. 

Usually, `e` represents the user's intent (to switch tabs or delete an item, etc), and `f` computes the world in which this intent has been realised. If the intent was to delete item 2, then the world has to be changed so that item 2 is no longer there. If the intent was to switch tabs then perhaps a twirly needs to be displayed and an HTTP GET must be initiated to get data.

> This formula is a very schematic description. In practice, we know that `f` is called an `event handler` and that there is a different one registered for each event. We use `reg-event-db` or `reg-event-fx` to do handler registration.

Except `f` doesn't need the state of the entire world `w` to do its job.  It will only need a small subset.

Let's call that subset `cofx` (pronounced co-effects). And, further, let's say there's a function `g` which can extract `cofx` from `w`. This `g`  can obtain the subset of `w` which is necessary for `f` to compute the implications of `e`. 

Our schematic depiction becomes:
```
cofx = g(w, e)
w' = f(cofx, e) 
```

> Note 1: the `cofx` needed for one event, might be different to that required for another event. So we provide `e` to `g` - so it can know what `cofx` is required.

> Note 2: the state of the application, `s`, is usually an important part of `cofx`. In fact, for many events, `f` only needs `s` (and nothing else) to do its job, meaning that `cofx = s`. For other events, `f` might need to know other details like the current datetime or if the browser window is maximised, in which case `cofx` contains more data.  We use `reg-event-db` when `cofx = s` and `reg-event-fx` otherwise.

> Note 3: Yes, I name things. I wish I was clever enough to use a [`point free style`](https://lispcast.com/what-is-point-free-style/) but sadly, I'm not.

Another tweak is necessary. `f` doesn't actually compute the new state of the world, `w'`. 
Instead, it computes the set of side-effects which, when actioned, would produce the new world `w'`. 

So there's actually three steps: 
```
cofx = g(w, e)
effects = f(cofx, e) 
w' = h(w, effects)
```

We've added a 3rd function `h`  which takes the `effects` calculated by `f`, and actions them - makes them real, which is a mutative and effectful process. The world will be changed (including the application state `s`, often).  `f` produces instructions and `h` makes them happen.

`g` and `f` deliver domino #2

`h` is domino #3

There is a good argument to say that `g` should be its own domino, instead of being subsumed into #2. But that didn't happen. 

`f` is at the centre of the process. Before it, `g` is just preparation - pulling together necessary information into `cofx`.  And after it, `h` is merely performing the instructions supplied by `f` - making stuff real - doing some unpure leg work.

## Proposal 

Domino #2 currently covers two things:  `g` and `f`. 

But each of those functions should be a domino in its own right.

**Comment by davidpham87** [comment]
I know it is only math, but does  `f`event needs to know about `e` in the mathematical formulation? Since `e` could also be part of the `cofx` forwarded from `g`?

**Comment by mike-thompson-day8** [comment]
@davidpham87 Yes, in theory, you are correct. However practically, for ease of restructuring, it has always been useful to have `event` separate.

**Comment by mike-thompson-day8** [comment]
After doing a lot of recent work on the docs (this round of work is coming to a close now), I have no more appetite for making this change.  I'm still sure it would be a correct change to make. But it just breaks too many words, too many diagrams, etc.  So I've decided that cost-benefit wise it isn't worth it. 

Closing.
