### ISSUE TITLE
reaction

### ISSUE THREAD

**Issue by zajac** [Day8/re-frame#58]
I have more like a question than bug report. 
Can I just subscribe to some subscription without producing hiccup and messing up with React itself? All I want is to listen to some change in model and update some complicated JS component (CodeMirror). 
Maybe the place to ask is Reagent repo but maybe you know how to deal with it.
This will not work:
```
(register-sub
  :editor
  (fn [db _]
    (get-in db [:shared-model :editor])))

(let [s (subscribe [:editor])]
  (reaction
    (println @s)))
```
Thanks in advance.

**Comment by mike-thompson-day8** [comment]
Resolved here:  https://github.com/reagent-project/reagent/issues/127
