### ISSUE TITLE
Remove Gitbook Builds?

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-frame#580]
Remove the Gitbook generation parts of the repo and decommission the associated build process.  

## Why?  

**_First_**, the Gitbook generation is unused, I think. There are no public-facing links to it anywhere, as far as I’m aware.  For the record, [here is the link](https://d8.gitbooks.io/re-frame/content)

**_Second_**, I'm getting emails from GitBook telling me to update the integration because the existing integration is now legacy and will stop working soon.

**_Third_**, I’m not confident it is working 100% correctly any more (although it might be)?  Eg. I just found that `/docs/INTRO.md` seems to hold a copy of `/README.md` ... except it hasn't been kept up to date with the small adjustments made to `/README.md` over time, and discovering that is probably the last straw that drove me to make this issue. 

**_Fourth_**, the contributor who wanted to see GitBook used is no longer around and even when they were around they only progressed this project part the way (as I understand it). 

## Doing The Removal

Notes on removing: 
  - See [this PR](https://github.com/day8/re-frame/pull/414) for the original details
  - And [these aliases](https://github.com/day8/re-frame/blob/master/project.clj#L72-L91) 
  - There will be some webhook somewhere to trigger the build process

## And Then? 

Perhaps we can then regroup on docs and figure out a new way forward for creating a nice looking set of docs from the underlying `.md` files we have in `/docs`. (I don't think that Gitbook ever looked very good anyway … although obviously it was a little better than the current straight GitHub `.md` files)

**Comment by include** [comment]
maybe this https://squidfunk.github.io/mkdocs-material/getting-started/ or any other simple alternative.

**Comment by superstructor** [comment]
- [ ] Remove Installed GitHub app which does GitBook integration 
- [ ] Remove the Gitbook entry for re-frame 
- [ ] Remove code from the re-frame repo (i.e project.clj aliases)

**Comment by mike-thompson-day8** [comment]
@include  discussion is now at https://github.com/day8/re-frame/issues/582
