### ISSUE TITLE
Remove TOC from docs

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-frame#581]
A long time ago, we added a way to automatically generate a Table of Contents (TOC) for `/docs/*.md` 

But that was a mistake and I ended up commenting out all the TOC.  But the cruft from this decision is still stuck in all the docs and there's more cruft in `/bin` etc.  For example, if you look at the end of  `docs/Coeffects.md` you'll see it all commented out like this ... 

```
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->
<!-- ## Table Of Contents -->

<!-- - [What Are They?](#what-are-they) -->
<!-- - [An Example](#an-example) -->
<!-- - [How We Want It](#how-we-want-it) -->
<!-- - [Abracadabra](#abracadabra) -->
<!-- - [Which Interceptors?](#which-interceptors) -->

<!-- END doctoc generated TOC please keep comment here to allow auto update -->
```

So let's clean up this mistake.  Let's just rip it out of `/docs/*.md`.  And then remove the stuff in `/bin` etc.  Anything else?

To provide information about what has to be undone, here is the original commit:
https://github.com/day8/re-frame/commit/d9cdb53c07c5b43d9cd3ef6a6a6a6229970eeeec

**Comment by superstructor** [comment]
Removed.
