### ISSUE TITLE
Make A Proper Website 

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-frame#582]
re-frame needs the beautiful, grown-up website it so richly deserves. 

Content is king and we already have that in the `README` and `.md` files within `/docs`.

Which means:
  - identify a static site generator to pull the existing content together with Navigation etc
  - host via Github Pages
  - generate using Github Actions

Technical requirements for the static site generator include: 
  - looks good out of the box - minimal design work required - obviously first impression count
  - a few tabs across the top (Home, Docs, API, Releases, 3rd Party)
  - Navigation on the left (telescopic/collapsible tree), particularly for the lengthy "Docs" pages
  - Page TOC on the right? 
  - content is about 60 to 80 characters wide for the optimal reading experience. 
  - Textual Search 
  - The ability to integrate Klipse to get live coding on some pages.

This might be a good base:
https://squidfunk.github.io/mkdocs-material/getting-started/

Also, Gatsby has always looked interesting, but I couldn't find a theme which matches the requirements.

**Comment by mike-thompson-day8** [comment]
Obviously there'll need to be a "Shop" too.  Where you can get re-frame T-Shirts.

**Comment by martinklepsch** [comment]
Do I get commission for the logo? :joy:

**Comment by mike-thompson-day8** [comment]
> Do I get commission for the logo?

Absolutely.  You'll soon be rubbing shoulders with Rusian oligarchs and Saudi Princes. And probably best if you work out ahead of time which disease you're going to cure. You don't want a pesky decision like that sprung on you.

**Comment by mike-thompson-day8** [comment]
Via https://twitter.com/sfyire/status/1257650784822611970
consider  https://docusaurus.io

**Comment by mike-thompson-day8** [comment]
@martinklepsch   You might hate me for this (I hope not) but I have a friend who is a graphic artist and she offered to look at the re-frame logo and refine it.  

She has made the following suggestion which is **entirely** in keeping with your wonderful approach.  I wondered if you would object if we used this refined version?  Suffice it to say, you will continue to to receive all cashflow from T-shirts. 

![image](https://user-images.githubusercontent.com/3033376/82109963-fed06d80-977d-11ea-836d-a7274e8711fd.png)

**Comment by mike-thompson-day8** [comment]
The new re-frame website is available here in a beta state, for comment:
https://day8.github.io/re-frame-wip/

**Comment by martinklepsch** [comment]
@mike-thompson-day8 I love it! Thanks for asking, very kind of you.

**Comment by simongray** [comment]
It’s pretty and the you seem to care about accessibility (nice), but it - kind of like the official Clojure website - really needs an illustratory code snippet on the frontpage. If you follow the “Get started” link there’s another five pages to read before you get to the first tiny code snippet.

In the old (awesome) long-form README.md you could quickly scroll down to see some code and get a feeling of what Re-frame is about and that is now sadly gone. Asking the user to commit to reading several pages before they get to see any code is way, way too much.

The writing itself is top-notch (seems to be based on the old README.md), but I think hiding the code away 6 pages in is detrimental to the goal of making Re-frame more accessible to newcomers. Please consider putting the code up front.

**Comment by mike-thompson-day8** [comment]
@simongray  
Thank you for the feedback.  You are right.  It is roughly the same content as the README, just split into different files and that creates a different impression. Anyway, I'll put some thought into it. I might start with some simple Reagent stuff, to give some early code. 

Question:  It sounds like the original README worked for you.  When you originally read it, did you approach it as an experienced Clojure person, or coming from JS?

**Comment by simongray** [comment]
@mike-thompson-day8 

> It sounds like the original README worked for you. When you originally read it, did you approach it as an experienced Clojure person, or coming from JS?

I hadn't used JS other than very basic "DHTML" back in the day. Not any of the the modern stuff.

Some time in late 2017 I knew I wanted to make a SPA and had just started learning Clojure. I did some research and ended up using Re-frame. I think I just liked the high-level concepts and knew I needed someone else to structure my SPA, since learning Clojure/ClojureScript itself was difficult enough. Re-frame's strong point is really giving ClojureScript newbies a plan for how to structure their SPA. 

To be honest, while I like the Re-frame README (explaining the rendering loop), what really sold me on reagent+Re-frame were Eric Normand's incredible guides. They contain lots of simple examples and really help to illustrate the strengths of reagent and Re-frame, but mostly they just demystify what a lot of the buzzwords actually mean.
