### ISSUE TITLE
API Documentation Generation and Deployment

### ISSUE THREAD

**Issue by superstructor** [day8/re-frame#587]
Issue #216 is now fixed, which is great because we can now create good API docs.  But that creates another issue (this one).  We now need to automatically generate re-frame’s API docs and put them somewhere, probably via GitHub Actions.  Perhaps look at Reagent for inspiration (it has an API link in its docs).  Also, isn’t there already a central site which aggregates the docs from various Clojure projects?  Is that cljdoc? If so, perhaps just point to there?  See #576 ??

**Comment by martinklepsch** [comment]
Feel free to ping me directly in Slack if you have any questions around using cljdoc for this. Here are the [current docs for re-frame on cljdoc](https://cljdoc.org/d/re-frame/re-frame/0.12.0).

**Comment by superstructor** [comment]
Codox generates files for the website [in the GitHub Actions workflow](https://github.com/day8/re-frame/blob/master/.github/workflows/docs-workflow.yml#L15).

Cljdoc config has been [moved to this repo](https://github.com/day8/re-frame/blob/master/doc/cljdoc.edn) and is [verified on continuous integration](https://github.com/day8/re-frame/blob/master/.github/workflows/continuous-integration-workflow.yml#L67).
