### ISSUE TITLE
Bad Links in new Docs site

### ISSUE THREAD

**Issue by haraldpusch** [day8/re-frame#594]
Just scanned over the website and found a couple bad links.

- Top Navigation -> "Resources" links to https://day8.github.io/re-frame/external-resources.md
- In "Docs": Side Navigation -> "More Advanced" -> "App Structure" links to https://day8.github.io/re-frame/app-structure.md
- In "Docs": Side Navigation -> "More Advanced" -> "Eek! Performance Problems" links to https://day8.github.io/re-frame/performance-problems.md

You may want to update CONTRIBUTING.md as well, as it references `docs/DEVELOPER_NATES.md` which doesn't seem to exist any more.

**Comment by mike-thompson-day8** [comment]
Many Thanks! 

I have merged your PR and corrected CONTRIBUTING.md
