### ISSUE TITLE
Bad link for resources in new site

### ISSUE THREAD

**Issue by JulienRouse** [day8/re-frame#597]
When clicking on the 'Resources' tab in the header of the new website, (url https://day8.github.io/re-frame/external-resources.md), it lead to a 404 message.
![2020-05-16_14h31_29](https://user-images.githubusercontent.com/5703619/82127490-f417d780-9781-11ea-96f5-9d9d7c4d45d6.png)

**Comment by mike-thompson-day8** [comment]
Thanks. Fixed now.
