### ISSUE TITLE
v1.0.0-rc2 throws error on React Native Expo

### ISSUE THREAD

**Issue by jgoodhcg** [day8/re-frame#604]
## Error message
```
addEventListener and attachEvent are unavailable
```

## Other info
I was working on updating deps and adding deps.edn support for projects created with [this create kit](https://github.com/jgoodhcg/create-expo-cljs-app).

`v1.0.0-rc2` throws the error above when the app first starts. `v0.12.0` works fine.

**Comment by superstructor** [comment]
Thanks for the report @jgoodhcg, you've indeed found a bug 🐛 👍 

This error is occurring [here in the google closure library](https://github.com/google/closure-library/blob/803aa52f65e59ee354ad40f89f18b5d847523f73/closure/goog/events/events.js#L271) due to my unconditional [use of the goog events api here](https://github.com/day8/re-frame/blob/d0c2239900e21b700882e3e8dd2f6477b067a644/src/re_frame/interop.cljs#L9).

The fix will be to first check that the environment (e.g. react native expo) supports the event APIs prior to calling it. We'll get this done in `1.0.0-rc3`.

**Comment by superstructor** [comment]
This might be fixed by #615 so I have released `1.0.0-rc3` ad left this issue open for feedback @jgoodhcg

**Comment by jgoodhcg** [comment]
It looks like there is still a problem. 
![Screenshot_20200629-194431](https://user-images.githubusercontent.com/10408149/86066897-6e09d480-ba41-11ea-8b4c-8ef018ea580b.png)

**Comment by neural-works** [comment]
The problem stills on 1.0.0-rc5

**Comment by superstructor** [comment]
In `1.0.0-rc6` we have added a `try`/`catch` that ignores the exception on environments that do not support `addEventListener` via the `goog.events/listen` API (e.g. React Native).

This fixes the issue but does mean that in React Native `:loaded?` in settings will never be set to true, so you'll continue to get superfluous duplicate event handler warnings when hot reloading code (e.g. via shadow-cljs, figwheel etc).

If you have any suggestions on the following please let us know @neural-works @jgoodhcg 
1. What is a good way for re-frame to detect that it is in the React Native environment ?
2. Is there an alternative in React Native to `goog.events/listen` on `js/self` (i.e. the global object, usually `js/window`) to listen for the `"load"` event ? Or in other words, to execute a fn when all scripts have loaded ?

**Comment by superstructor** [comment]
Reopened awaiting response to above. Any feedback on above two questions @neural-works @jgoodhcg on how to detect being in React Native ?

**Comment by jgoodhcg** [comment]
I have not had the to develop a library that runs on any platform but a quick google search found [this option](https://stackoverflow.com/a/39473604) for detecting environment.

I've not seen anything for executing a function when scripts load.

**Comment by jgoodhcg** [comment]
Updated to `1.1.1` today and it seems to be working :smile:. Thanks!
