### ISSUE TITLE
API docs do not pick up the version 

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-frame#611]
![image](https://user-images.githubusercontent.com/3033376/85010209-f61aef00-b1a2-11ea-9216-47bbf8a02725.png)

**Comment by superstructor** [comment]
Turns out this actually works on a local git checkout.

Its something to do with the differences in the git history available on GitHub Actions ci vs a local dev checkout.

I attempted to provide full git history by configuring the checkout action in 3988b9f but that didn't resolve the issue.

**Comment by mike-thompson-day8** [comment]
Also:
  - many of the docstrings use markdown format but that is not showing up see [how here](https://github.com/weavejester/codox#docstring-formats)
  - we need to add the building effect handlers - perhaps [using this?](https://github.com/weavejester/codox#documentation-files)

**Comment by nathell** [comment]
Meta question: is codox even necessary, given the existence of [cljdoc](https://cljdoc.org/d/re-frame/re-frame/1.0.0/doc/readme)? It's automatic and arguably nicer than codox (eg supports markdown in docstrings). It does make a mess of re-frame's docs as they currently stand, but that should be easily fixable.

I've pondered codox for my library and decided to go full cljdoc, because it places less burden on me as a maintainer.

**Comment by mike-thompson-day8** [comment]
@nathell 
Doesn't cljdocs just use codox? 
Anyway, we'll stick with what we have now.  codox supports markdown docstraings.  Our goal is to host our own API docs, along with the rest of the docs. We're too far into the current approach this change course.

**Comment by superstructor** [comment]
>  It does make a mess of re-frame's docs as they currently stand, but that should be easily fixable.

This is the core issue with maintaining cljdocs in addition to our own hosted website at http://day8.github.io/re-frame/

Its actually *not* easily fixable. Getting cljdocs to render the docs as intended to be viewed on the website is a large task in of itself, doesn't allow enough customisation to do some things we want (e.g. live interactive code) and we'd constantly be maintaining *two* different styles/presentations of the same docs. As such it was decided that cljdocs intentionally only displays the `README.md` which links to the website so we only have to make one copy of the docs look good.

**Comment by mike-thompson-day8** [comment]
All sub-tasks completed.  

Closing
