### ISSUE TITLE
Copy docstrings into core API

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame#62]
I'm not sure what options there are in ClojureScript, but in Clojure Zach Tellman has Potemkin with [import-vars](https://github.com/ztellman/potemkin#import-vars). From ztellman/potemkin#31 it doesn't look like Potemkin supports this in cljs.

**Comment by mike-thompson-day8** [comment]
I can see the need.  But I don't see any way of automating it.  So it would involve manual duplication which seems an unattractive idea.  Hmm.  Not sure what to.

**Comment by mike-thompson-day8** [comment]
Dumping this associated link in here, so it isn't forgotten: 
http://side-effects-bang.blogspot.com.au/2015/06/importing-vars-in-clojurescript.html

**Comment by danielcompton** [comment]
Looks very promising, although it will mess up Cursive code completion and analysis until it supports macros or adding library stubs :(

**Comment by danielcompton** [comment]
Relates to https://github.com/cursiveclojure/cursive/issues/944.

**Comment by mike-thompson-day8** [comment]
Clojure doesn't provide an easy way to make this happen, so I'm going to close this.
