### ISSUE TITLE
Documentation Suggestions

### ISSUE THREAD

**Issue by phronmophobic** [day8/re-frame#626]
I really love the re-frame documentation. There were a few places I had some trouble following and I just wanted to summarize my experience. I'm not sure any of these suggestions are actual improvements, but maybe some of them are helpful.

Here's the corresponding pull request:
https://github.com/day8/re-frame/pull/625

**reg-sub**
I think `reg-sub` is one of the core re-frame functions and I had some trouble following the description in http://day8.github.io/re-frame/subscriptions/#reg-sub

I'm still not sure what the 2 arguments to the signals function are. The arguments in the example are `_` and it's not described in the section below.

Similarly, I'm not sure what the 2nd argument to the computation function is.

**Dominoes 1-6**
In general, I had trouble remembering which domino number corresponded to which domino category. I've tried including the Domino category (eg. Event Handling) whenever a domino is mentioned.

**Layers 1-4**
In general, I had trouble remembering which layer number corresponded to which layer category. I tried replacing the layer numbers with their corresponding categories. 

There's a lot of new (to me) jargon introduced (eg. coeffects, interceptors, etc) in addition to 6 dominoes and 4 layers. It's much easier for me to follow descriptions of "materialized view" subscriptions rather than descriptions of layer 2 subscriptions.

**Navigation**

It's weird to me that part of the navigation is on the left side the page and part of the navigation (the table of contents) is on the right side of the page.

There's not that many sections on the left side navigation. I would prefer if the subsections were expanded by default.

The subsections in the table of contents work well for when you're reading the guide from top to bottom. Some of the titles lack context if you're searching for a specific part of the guide.

The docs search bar at the top is actually really good. I'm used to the search bar being almost useless. Before I realized that the search was actually good, I would try to find a relevant section of the docs by simply going through the navigation. Not sure how to let people know the search bar actually works well ¯\_(ツ)_/¯.

**Comment by phronmophobic** [comment]
Awesome!

**Comment by mike-thompson-day8** [comment]
Thanks again.
