### ISSUE TITLE
re-frame.settings throws - interop/on-load undefined

### ISSUE THREAD

**Issue by brjann** [day8/re-frame#638]
I just upgraded to 1.0.0

As soon as I start the app, I get the following error in the console `Uncaught TypeError: Cannot read property 'call' of undefined at settings.cljc:13`

Lines 13-14 are in settings.cljc are
`(interop/on-load
       #(swap! store (fn [m] (assoc m :loaded? true))))`

In the cljs REPL, `interop/on-load` evaluates to nil

**Comment by mike-thompson-day8** [comment]
@brjann 
Could you confirm that this is in a browser environment, not, say, Node or React Native.

**Comment by brjann** [comment]
@mike-thompson-day8, yes! Chrome 83.0.4103.116

**Comment by superstructor** [comment]
@brjann 
We can't replicate this problem on the example apps or on a couple of private commercial apps. 

Any chance you can create a minimal repo which shows the problem?  Perhaps use `re-frame-template` for a quick scaffold?

**Comment by brjann** [comment]
Now the bug disappeared and I can't reproduce it. I fear that this may have been due to browser cache, maybe the interop namespace from the previous re-frame version I had installed was loaded instead of the one in 1.0.0. 

I'm terribly sorry for bothering you with this!

**Comment by superstructor** [comment]
Thanks for following up @brjann 👍
