### ISSUE TITLE
New 1.1.0 docs for dispatch-later are incorrect

### ISSUE THREAD

**Issue by danielytics** [day8/re-frame#642]
The [new `1.1.0` docs](http://day8.github.io/re-frame/api/#api-builtin-effects.html/dispatch-later) show example of `dispatch-later` as:

```clojure
{:db  new-db 
 :fx  [[:dispatch-later {:ms 200 :dispatch [:event-id "param"]}]]}
```

but `dispatch-later` expects a vector of maps:

```clojure
{:db  new-db 
 :fx  [[:dispatch-later [{:ms 200 :dispatch [:event-id "param"]}]]]}
;                       ^
```

**Comment by superstructor** [comment]
Thanks @danielytics Good spotting! 👍

**Comment by danielytics** [comment]
No problem!

Without the vector would be nicer, as it would be consistent with the new way of doing things, but it would break backwards compatibility. Unless a new version was added and the existing one deprecated. Maybe `:dispatch-after` or something like that. Probably not worth it, at least not now.

**Comment by superstructor** [comment]
> Without the vector would be nicer, as it would be consistent with the new way of doing things, but it would break backwards compatibility.

Done in `1.1.1` ✔️ Without breaking backwards compatibility.

Thanks for the suggestion @danielytics

**Comment by danielytics** [comment]
Aha, you just check if its a map or not. Perfect! :+1:
