### ISSUE TITLE
Incorrect docstring for `re-frame.core/debug`

### ISSUE THREAD

**Issue by p-himik** [day8/re-frame#676]
The docstring says:
```
An interceptor which logs/instruments an event handler's actions to
  `js/console.debug`
```

The actual implementation in `re-frame.std-interceptors` uses:
```
(console :log "Handling re-frame event:" (get-coeffect context :event))
[...]
(console :log "only before:" only-before)
(console :log "only after :" only-after)
```

Apart from using an incorrect level, the docstring also mentions `js/console`, which is incorrect.

I'd argue that both places should use/mention `re-frame.core/console`. And definitely use/mention the same logging level, but whether `:log` or `:debug` I'm not sure.

**Comment by jimpil** [comment]
I would also add the fact that the diff parts are console-printed completely bare - i.e. as Objects. That is not very helpful, unless you have extra tooling in place... I would have expected everything to to be printed out as EDN, otherwise what's the point? How am I expected to make sense of these Objects? Is no-one else having this problem?

**Comment by p-himik** [comment]
@jimpil Do you have `cljs-devtools` installed?

**Comment by jimpil** [comment]
That's the extra tooling I was referring to - I guess I can install it, but I kind of feel I shouldn't have to...

**Comment by p-himik** [comment]
In an ideal world, CLJS runs directly in a browser. ;) But `cljs-devtools` is a must-have tool - same as `re-frame-10x`, React DevTools, shadow-cljs build report and so on.

Printing the EDN itself as a string would be _much_ less useful - no interaction, potential data size issues, no proper representation for types that EDN doesn't handle, inability to drill down (e.g. you can right-click an expanded object when you have `cljs-devtools` and save it in the global scope under its own name).

**Comment by mike-thompson-day8** [comment]
@jimpil I second the previous comment. `cljs-devtools` is essential when doing anything in clojurescript.

**Comment by mike-thompson-day8** [comment]
Checking so the solution to the original report is just to use `(console :debug ...)`  instead of `(console :log ...)`

**Comment by kimo-k** [comment]
Going with #2 for now. @mike-thompson-day8
