### ISSUE TITLE
FAQ #2 incorrect

### ISSUE THREAD

**Issue by mpisanko** [Day8/re-frame#68]
I've tried two versions (using re-frame 0.4.0 and 0.4.1). The subscription :edited does NOT work whereas the :edited-org does. Is it problem with user or FAQ?

(register-sub
  :trainings
  (fn [db _]
    (reaction (vals (:trainings @db)))))

(register-sub
  :editing
  (fn [db _]
    (reaction (:editing @db))))

(register-sub
  :edited
  (fn [db _]
    (let [trainings (subscribe [:trainings])
          editing (subscribe [:editing])]
      (reaction (get @trainings @editing {})))))

(register-sub
  :edited-org
  (fn [db _]
    (reaction
      (let [trainings (:trainings @db)
            editing (:editing @db)]
        (get trainings editing {})))))

**Comment by mike-thompson-day8** [comment]
Did you mean:
```
register-sub
:trainings
(fn [db _] ))    <--- changed
```

**Comment by mpisanko** [comment]
Yeah,
it's markdown (silly user again) that stripped the stuff of it. Let's try again:
```
(register-sub
  :trainings
  (fn [db _]
    (reaction (vals (:trainings @db)))))

(register-sub
  :editing
  (fn [db _]
    (reaction (:editing @db))))

(register-sub
  :edited
  (fn [db _]
    (let [trainings (subscribe [:trainings])
          editing (subscribe [:editing])]
      (reaction (get @trainings @editing {})))))

(register-sub
  :editd
  (fn [db _]
    (reaction
      (let [trainings (:trainings @db)
            editing (:editing @db)]
        (get trainings editing {})))))
```

**Comment by mike-thompson-day8** [comment]
In `edited-org`  did you mean
```
(register-sub
  :trainings
  (fn [db _]
    (reaction (:trainings @db))))      ;;  removed  "vals"
```
