### ISSUE TITLE
README.md -- where is :name-query defined?

### ISSUE THREAD

**Issue by jdeisenberg** [Day8/re-frame#69]
The README references 

````(let [name-ratom  (subscribe [:name-query])]````

and later defines `:customer-query`, but not `:name-query`. Is this intentional, an error, or am I just missing something obvious here?

**Comment by mike-thompson-day8** [comment]
I think the README is correct.  It does change from a name query to a customer query around that point.  See for example reference to `(subscribe [:customer-query "blah"])`

**Comment by danielcompton** [comment]
I think this can be closed now?
