### ISSUE TITLE
reaction doesn't trigger a re-render for array

### ISSUE THREAD

**Issue by squest** [Day8/re-frame#70]
First of all, thanks for this great "framework" :+1: , just been aware of it yesterday and already spent the next 20hours on it (it's really fun to play with :)) 

Anyway, I have an app-db like this

```clojure
(def app-db
  (->> (range 2015 2023)
       (map #(vector % (int-array 10 0)))
       (into {})
       (assoc other-data :finance)))
```

Somehow the subscription/reaction doesn't work for array (not reactive enough, the dispatch fn changed the app-db, yet doesn't trigger re-render components that subscribed to it). It is however changed once I navigate to other page and then go back to that page (an act which mutate the value of app-db). When I changed it to a vector then it works as expected.

I haven't look into the source code yet, but my guess is that the mutation inside array-cells won't be counted as an object change since the reference to the object remain unchanged and thus do not trigger re-rendering.

If it's intended to be that way so be it (it enforces value-based state anyway, instead of a reference-based). But just in case it wasn't, then a heads-up would probably be nice (I'm a rookie in this front-end world, so probably it's just me that is unaware of this behaviour).

Thanks

**Comment by danielcompton** [comment]
Hi @squest, I'm not totally clear on what you're trying to do here, and I didn't realise you could create an int-array in ClojureScript. However your most general point is true: Re-Frame (and much of the Clojure ecosystem) leverages value's, not references for state tracking. So you're right that any mutations to a JS array will not be picked up by Reagent's change tracking.

**Comment by squest** [comment]
Thanks for the reply @danielcompton , I am trying to build a numbers/excel-like matrix-cells web app for financial simulation which I think best modelled using array-like data structure (for easy in-place mutability). However, now I prefer using value-based structure like map & vector instead (just discovered that Clojure has this update-in fn to easily manipulate such structure).

Relevant to this issue I'm raising (maybe it's also the issue for ratom), probably it's better to inform the users that the re-rendering won't be triggered for reference-based type (although it's quite obvious for me now, it's still a gotcha).

So should we close this issue then?

**Comment by mike-thompson-day8** [comment]
@squest  I'm going to close this without changes being made to docs. While it managed to trip you up, I'm not sure its a common enough problem to warrant specific warnings (not sure where I'd put them in any case).
