### ISSUE TITLE
re-frame + pyccoon

### ISSUE THREAD

**Issue by cryptonomicon314** [Day8/re-frame#72]
Pyccoon is a Marginalia-like tool, to which I'm trying to add support for hyperlinks in the source (currently only for clojure and clojuresccript).
I used re-frame as test project, and would like your feedback. Link [here](http://cryptonomicon314.github.io/pyccoon-cljs-re-frame/) (this was made with my personal branch, not the official one)
Do you like the style? Are the hyperlinks useful?

**Comment by mike-thompson-day8** [comment]
First, I really appreciate the effort you've put in here. Thankyou.  But ....  I'm not sure why,  but I've never found myself drawn to this kind of approach.  I see the value intellectually, but equally I then find myself not really using it.  So the proof of the pudding is in the non-eating. Puzzling.   But perhaps that's just me.  I might be a bad litmus test. I'd sample opinions more widely.

**Comment by danielcompton** [comment]
I think this can be closed now. Looks interesting, but as Mike said, I'm not sure if I would actually use it. Feel free to announce it on the Clojure list if you haven't already, I'm sure others would be interested.
