### ISSUE TITLE
Middleware Wiki Suggestion

### ISSUE THREAD

**Issue by estsauver** [Day8/re-frame#73]
Hey @mike-thompson-day8,

You might be interested in the explanation/description of middleware at https://github.com/boot-clj/boot/wiki/Tasks. I thought the picture was pretty good. I saw the middleware wiki page has quite a bit of effort put into it, and there diagram might be helpful.

Cheers,

~Earl

**Comment by mike-thompson-day8** [comment]
A picture is worth a 1000 words, so we'll gratefully steal that diagram. But we'll need a re-frame version.

**Comment by mike-thompson-day8** [comment]
As a part of [version 0.8.0 middleware is out and Interceptors are in](https://github.com/Day8/re-frame/blob/develop/CHANGES.md#080--20160818) so I'm closing this.  Although any additions [to the docs](https://github.com/Day8/re-frame/tree/master/docs) will be gratefully accepted.
