### ISSUE TITLE
[Enhancement]: Allow nil to be used as a value for :fx

### ISSUE THREAD

**Issue by bowbahdoe** [day8/re-frame#737]
### What do you suggest?

Currently this outputs a warning, because `nil` is not sequential.

```
{:fx nil}
```

Would be nice to have it be just a supported way so patterns like

```
{:fx (if condition (alert-fx/alert "abc") fx/none)}
```

are unneeded we could instead

```
{:fx (when condition (alert-fx/alert "abc"))}
```

**Comment by mike-thompson-day8** [comment]
Note: it is slightly more verbose but this current works:

`{:fx [(when condition (alert-fx/alert "abc"))]}`

**Comment by bowbahdoe** [comment]
That would make our fx abstraction not composable. Currently we define an "effect" as the whole vector of effects

```
;; STUFF -> EFFECT
(defn alert [stuff]
  [[::alert stuff]])
  
;; STUFF -> EFFECT
(defn log [stuff]
  [[::log stuff]])
```

This has the benefit of letting more complex stuff like

```
;; List<EFFECT> -> EFFECT
(defn in-order [& effects]
  (vec (apply concat effects)))
  
;; STUFF -> EFFECT
(defn something-interesting-happened [stuff]
    (in-order (alert stuff) (log stuff)))
```

**Comment by superstructor** [comment]
I don't think silence on nil is OK esp in the context of this error message being in place for some time. However it needs to be changed to a warning so that users are not misled into thinking that nil is unsupported - if you intended it, then it is fine.

**Comment by bowbahdoe** [comment]
...what?
