### ISSUE TITLE
[Enhancement]: Warn on `subscribe` being used outside of a reactive context

### ISSUE THREAD

**Issue by p-himik** [day8/re-frame#740]
### What do you suggest?

People often make the mistake of using `subscribe` in a JS event handler or in a re-frame event handler, probably in other places. To know better, one have to carefully read the documentation, which people often don't do.

It would be better to warn them about `subscribe` being used incorrectly with a link to the right section of the documentation.

**Comment by qleguennec** [comment]
On a side note, I've not been entirely convinced that this pattern is effectively an issue (according to the docs, it "might create a memory leak", can't it be more precise?). I'm a dev in an fairly old re-frame project and this pattern is used extensively, and it seems to work just fine. 

Is the purpose of the warning only to warn that the subscription won't be reactive, or will there be something else added to it?

**Comment by p-himik** [comment]
Subscriptions are cached and the cached is pruned from an unused subscription only when the last watcher of that subscription is removed.
When a sub is never used in a reactive context, there are no watchers at all. It's still added to the cache but it's never removed - creating a memory leak. The leak is only potential because the same sub could also be used in a reactive context.

**Comment by dannyfreeman** [comment]
Another thought would be to detect if a call to subscribe is happening in a reactive context, and if it is not bypass caching the subscription in the first place. That would avoid the memory leak.
