### ISSUE TITLE
[Enhancement]: Allow enrich to return `nil`

### ISSUE THREAD

**Issue by NoahTheDuke** [day8/re-frame#750]
This just bit my ass, but I don't necessarily think it's a bug, just a combination of misunderstood docs and hard-to-debug code. If the function `f` passed to `enrich` returns `nil`, then any changes performed by the `event-db` or `event-fx` handler will be discarded. The documentation [states](https://day8.github.io/re-frame/api-re-frame.core/#enrich) that it is expected to return a modified `db`. I thought that this worked the same as `event-db` and `event-fx` handlers where `nil` would ignore the operation (and thus use the given `db` value) but it instead uses the _original_ `db` value. For event handlers, this ends up being equivalent, but not for `enrich`.

I would like to suggest a couple solutions/changes to the below code to handle this scenario, as it was quite annoying to track down.

https://github.com/day8/re-frame/blob/7199496997cfb226311444f4402d1bda5798af60/src/re_frame/std_interceptors.cljc#L205-L206

1) Rename `db` to `previous-db` and assign `(f db event)` to `new-db`, and then `(assoc-effect context :db (or new-db previous-db))`. This allows for `enrich` functions to return `nil` while not dropping any changes that were performed by the event handler.
2) Assign `(f db event)` to `new-db`, and then ``(when (nil? new-db) (console :error "re-frame: enrich function" f "returned `nil`. This is very naughty."))`` or something similar so that the mistake can be traced.
3) Throw an error of some kind. This doesn't match with the rest of `re-frame`'s philosophy but should be listed anyways.

If any of these are amenable to you, I can open a PR for it.

**Comment by mike-thompson-day8** [comment]
Yes, a PR would be great. Thanks!

**Comment by superstructor** [comment]
Thanks for the report. Re 3. logging with `(re-frame.loggers/console :error ...)` might be more appropriate than throwing ?

**Comment by NoahTheDuke** [comment]
@superstructor Yeah, I intended these to be 3 separate potential solutions, not a single giant solution. I can implement whichever you'd like, just let me know.

**Comment by superstructor** [comment]
@NoahTheDuke agree with all. I think we should log the error instead of throw it. Look forward to the PR 👍🏻

**Comment by superstructor** [comment]
Reopened as #751 implemented 1. but at least 2. (logging) still needs to be done.

**Comment by NoahTheDuke** [comment]
I wrote the docs in my PR under the assumption that returning `nil` would be an expected behavior, so what kind of logging would you like? I feel like a `:warn` wouldn't be appropriate, given that I will be relying on this behavior deliberately in a somewhat high-volume code path.

**Comment by superstructor** [comment]
Sorry @NoahTheDuke I misread the issue/code when I posted my previous comment. The PR that has been merged is a sufficient solution 👍🏻
