### ISSUE TITLE
[Bug]: de-referencing re-frame.db/app-db inside subscription counts as changing data? 

### ISSUE THREAD

**Issue by scott-kl** [day8/re-frame#757]
### What happened?

This may not be a bug, but it was not the behaviour I expected and took a very long time to track down:

I have a utility fn load-entities which is called by a level 3 subscription handler.  It derefs app-db in order to perform lookups and merge those into the final result set of the subscription.  I'm not changing app-db at all, just reading.

Doing this, however, causes the same subscription (which de-refed the db) to be re-run on the next db change, even though it's input values remain unchanged.  Not sure why this is.  

I now perform the load-entities inside of the view component which is uglier but avoids the problem.

### Version

1.2.0

### What runtimes are you seeing the problem on?

Mozilla Firefox

**Comment by mike-thompson-day8** [comment]
I'm going to close this issue without change. 

A lot of work went into the docs, and I think they are quite clear about how your subscriptions should be structured, and how values from `app-db` should flow through them.  I'd encourage you to read https://day8.github.io/re-frame/subscriptions/#the-four-layers
