### ISSUE TITLE
[Enhancement]: Warning on re-registering subs / events (ie name collision detection) improvements

### ISSUE THREAD

**Issue by sirmspencer** [day8/re-frame#769]
1. It would be great to have the message show for a newly created sub and a hot reload.  We work in shadow-cljs and rarely do a full reload during dev.  I am not sure if this is possible, since a hot reload could just end up generating warnings for every sub in the file.

~~2. Setting to make the message a full error.  We don't have any use cases for re adding subs, so an error is more apt.~~

~~3.  A flag to fail during compilation would also be a great safety net.  Basically, we would want it to fail in the ci deployment when we run tests, or build the ubar jar.  Maybe a function that can check for duplicates, or any other warnings, that I can add to the test suite.~~

**Comment by sirmspencer** [comment]
It looks like I can do #2 with set-loggers!

**Comment by sirmspencer** [comment]
It looks like I can do #2 with set-loggers!

**Comment by sirmspencer** [comment]
I was also able to #3 with set loggers.  For anyone using shadow the key for both is to call set-loggers from a preload.

**Comment by mike-thompson-day8** [comment]
Regarding point 1, re-frame will warn about duplicates on the initial loading of code (up to the window "load" event) but after that, no warnings are issued (during hot code reloading).

**Comment by sirmspencer** [comment]
> Regarding point 1, re-frame will warn about duplicates on the initial loading of code (up to the window "load" event) but after that, no warnings are issued (during hot code reloading). See #204

I had a guess that might be the case
