### ISSUE TITLE
[Enhancement]: reg-event-fx :fx shorthand

### ISSUE THREAD

**Issue by sirmspencer** [day8/re-frame#770]
### What do you suggest?

Since any effect in the returned map for reg-event-fx can be added to the :fx effect, could you consider overloading reg-event-fx to take just the :fx vector as a response?

```
(reg-event-fx
  :example
  (fn []
    {:db {}
     :dispatch []}))
```
Can be written as 
```
(reg-event-fx
  :example
  (fn []
    {:fx [[:db {}]
          [:dispatch []]]}))
```
So an overloaded reg-event-fx could accept this as a response, and assume :fx.
```
(reg-event-fx
  :example
  (fn []
    [[:db {}]
     [:dispatch []]]))
```

**Comment by mike-thompson-day8** [comment]
I won't implement this idea because  it is generally better if there is only one way of doing things, and, anyway, there's already a variety of ways you can implement this choice yourself already: 
  - write and use an interceptor 
  - write and use your own version of `reg-event-fx`

**Comment by mike-thompson-day8** [comment]
Here's what I mean by an interceptor that does the job (untested):

```
(def rewire-effects
  (re-frame.core/->interceptor
    :id     :rewire-effects
    :after  (fn [context]
               (assoc context :effects {:fx (:effects context)}))))
 ```
 
Then, write your own version of `reg-effects-fx` to install this interceptor immediately after the event handler is called (based on existing code for `reg-effects-fx` [here](https://github.com/day8/re-frame/blob/master/src/re_frame/core.cljc#L108-L140)) 

```
(defn reg-event-fx2
  ([id handler]
   (reg-event-fx id nil handler))
  ([id interceptors handler]
   (events/register id [cofx/inject-db fx/do-fx std-interceptors/inject-global-interceptors interceptors rewire-effects (fx-handler->interceptor handler)])))
```
(untested)

Notice the use/placement of `rewire-effects`

**Comment by sirmspencer** [comment]
That's neat, I will try that.

"I regret putting the syntax sugar for subscriptions into re-frame core".  This is interesting.  I just saw that expansion of syntactic sugar and thought this idea was in line with that.
