### ISSUE TITLE
[Bug]: Multiple usage of the same standard interceptor creator in global doesn't work

### ISSUE THREAD

**Issue by joshcho** [day8/re-frame#775]
### What happened?

Using rf/on-changes multiple times and registering them via rf/reg-global-interceptor does not work.

So something like:
```
(rf/reg-global-interceptor (rf/on-changes + [:c] [:a] [:b]))
(rf/reg-global-interceptor (rf/on-changes identity [:d] [:c]))
```
will not work. I believe this is because rf/on-changes creates interceptors with the same id.

### Version

1.3.0

### What runtimes are you seeing the problem on?

Brave

**Comment by joshcho** [comment]
The workaround I am using at the moment is specifying the id like so:

(defn my-on-changes
  [interceptor-id & rest]
  (assoc (apply rf/on-changes rest)
         :id interceptor-id))

**Comment by kimo-k** [comment]
Hey @joshcho, interesting problem.

I considered changing the :id to include a hash of the args, but I think this would interfere with the simplicity of the library. Not all names in std-interceptors are factories, some are values. It's not so nice to have to hold onto an auto-generated id for later deletion. Dealing with extra arities or option maps for the id isn't so nice either.

While it would be nice if this just worked, I think it's okay to consider your use-case _non_-standard. I added some documentation for it.

If you'd like the ergonomics in your first example, consider:

```clojure
(defn my-on-changes [& args]
  (-> rf/on-changes
      (apply args)
      (update :id #(keyword (str (name %) "__" (hash args))))))
```
