### ISSUE TITLE
[Enhancement]: Subscriptions that return `nil` or `false` are evaluated regardless of what's in cache

### ISSUE THREAD

**Issue by p-himik** [day8/re-frame#777]
### What do you suggest?

This is how the cache lookup is implemented:
```clojure
(defn cache-lookup
  ([query-v]
   (cache-lookup query-v []))
  ([query-v dyn-v]
   (get @query->reaction [query-v dyn-v])))
```
And this is the important part of how it's used:
```clojure
(if-let [cached (cache-lookup query dynv)]
  cached
  (... compute the sub, cache, and return the result ...))
```

`if-let` returns its "else" branch when `cached` is either `nil` or `false`. And thus it always recomputes the sub value when it's `false`.
`if-some` would be better because then it would return the "else" branch only when the value is `nil`.
But a proper solution would use some singleton value with that `get` from the first block and check for it instead of using `if-let`/`if-some`.

**Comment by kimo-k** [comment]
Hey @p-himik, do you have a repro for this? 

The vals of the cache are reactions. I'm not sure what a user would do to put a nil or false in there.

**Comment by p-himik** [comment]
You're absolutely right, this issue is just a documentation of my poor judgement on that day.

**Comment by kimo-k** [comment]
Yeah it is kind of vexing when re-frame [double-derefs](https://github.com/day8/re-frame/blob/master/src/re_frame/subs.cljc#L119) things to get the job done, haha.
