### ISSUE TITLE
Schema in todomvc

### ISSUE THREAD

**Issue by newtack** [Day8/re-frame#78]
The readme recommends using the schema for app-db but the todomvc example does not use prismatic/schema. I tried but I am stumbling on the sorted-map. Can someone add this to the example?

**Comment by mike-thompson-day8** [comment]
Does this help?
https://github.com/Day8/re-frame/wiki/Debugging-Event-Handlers#3-checking-db-integrity

**Comment by mike-thompson-day8** [comment]
Sorry, now I see.  The problem is how to represent a `sorted-map` using Schema.

**Comment by whodidthis** [comment]
{:todos PersistentTreeMap}

**Comment by mike-thompson-day8** [comment]
Thanks @whodidthis
@newtack fixed in a5be3aaf3b8bed570ec23a7eb60417ae9a54757a
