### ISSUE TITLE
Citation credits

### ISSUE THREAD

**Issue by moohdyy** [Day8/re-frame#79]
The line of thought about flow (https://github.com/Day8/re-frame#flow)
were originally stated by Steve Grand.
(Richard Dawkins credited him correctly in his TED-talk:
http://www.ted.com/talks/richard_dawkins_on_our_queer_universe/transcript , minute 9:24)

**Comment by danielcompton** [comment]
Closed in #80

**Comment by mike-thompson-day8** [comment]
Thanks for the correction.
