### ISSUE TITLE
[Bug]: Reframe 10x is not being opened with ctrl+h after 1.6.0

### ISSUE THREAD

**Issue by Yacobh** [day8/re-frame#791]
### What happened?

After update to version 1.7.0 and up, the reframe 10x is not being opened in google chrome.

### Version

1.7

### What runtimes are you seeing the problem on?

Google Chrome

**Comment by hughdani** [comment]
Hi, according to the re-frame-10x changelog notes for 1.7.0, there was a change to the key binding. See what was [changed in 1.7.0](https://github.com/day8/re-frame-10x/blob/ce399742256106cadab39787efb5e122fd234248/CHANGELOG.md#changed-2) for details. Hope that helps!
