### ISSUE TITLE
[Enhancement]: Upgrade React dependency to React 18

### ISSUE THREAD

**Issue by Wegi** [day8/re-frame#792]
### What do you suggest?

Hey,

thanks for all your work. Is there any plans to upgrade the react dependency to react-18 in the near future, since reagent also migrated to 18 a while back.

**Comment by tejaskh3** [comment]
Hello Wegi, I can help you upgrading from react 17 to 18. Please assign this task to me.

**Comment by DonMiller9294** [comment]
Here is a link to react site to discuss what they are planning to do. I hope this helps you out. 

https://react.dev/blog/2021/06/08/the-plan-for-react-18

**Comment by kimo-k** [comment]
Hey @Wegi, as far as I know, re-frame already works with React 18 projects. Our react dependency is only used for CI/CD. for Do you mean upgrading the example projects, or do you have something else in mind?

**Comment by Wegi** [comment]
Hi kimo, yeah I meant the CI/CD dependency. Its not an urgent Issue, just saw it while upgrading the dependencies of a project I worked on.
