### ISSUE TITLE
Readme.md inaccuracy regarding Elm

### ISSUE THREAD

**Issue by bstro** [Day8/re-frame#82]
In the blog post at http://elm-lang.org/blog/announce/0.14, Elm evidently no longer uses `lift`, instead calling it `map`. re-frame's README.md states `While the mechanics are different, reaction has the intent of lift in Elm and defc= in Hoplon.` This might be confusing for certain readers.

**Comment by mike-thompson-day8** [comment]
Thanks for the correction.  Will roll out that tweak shortly.
