### ISSUE TITLE
Pour some sugar on register-handler

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame#87]
With the new debugging approach outlined in https://github.com/Day8/re-frame/wiki/Debugging, it could be nice to attach names to the (currently) anonymous functions that we're generating. This probably means a macro though which probably won't play nice with Cursive.

This:

```clj
(register-handler
    :toggle-done-db
    todo-middleware
    (fn [todos [id]]
      (update-in todos [id :done] not)))
```

could be rewritten as

```clj
(register-handler
    :toggle-done-db
    todo-middleware
    [todos [id]] ;; note no fn here
      (update-in todos [id :done] not))
```

or maybe as

```clj
(register-handler
    todo-middleware ;; no keyword name
    (fn toggle-done-db [todos [id]]
      (update-in todos [id :done] not)))
```

and we get the name of the function and turn it into a keyword for registration. We miss out on autocompletion and keyword renaming in Cursive too going this route though.

I'm not sure what the answer is but there's some things to think about. A similar situation exists for subscriptions.

**Comment by jaredly** [comment]
Another possibility -- if you've already got the whole file surrounded in the `trace-forms` macro, it could do the magic for you

**Comment by mike-thompson-day8** [comment]
For the moment, no sugar will be added. 
Better debugging and metrics will happen a different way in the next release.
I'll close this issue, as part of my string clean for [the v0.8.0 release](https://github.com/Day8/re-frame/blob/develop/CHANGES.md#080--20160819)
