### ISSUE TITLE
Log a warning if a subscription is called without a vector argument

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame#88]
`(subscribe :my-data)` will silently fail, when it should be `(subscribe [:my-data])`. It could be good to add validation to log something when a subscription is called without a vector as the argument.

**Comment by danielcompton** [comment]
This was an issue because I was using clairvoyant to wrap functions. It swallowed the error inside a group and didn't let it bubble up.

**Comment by thenonameguy** [comment]
Can we start a discussion about just allowing the use of `(subscribe :my-data)`, @mike-thompson-day8?

**Comment by danielcompton** [comment]
I'm pretty sure that breaks the symmetry of everything, I don't think I'd be in favour of this, having two types of argument going into the same function (keyword and vector) is generally avoided when possible.

**Comment by thenonameguy** [comment]
Fair enough, thanks for the response.
