### ISSUE TITLE
Add roadmap?

### ISSUE THREAD

**Issue by thenonameguy** [Day8/re-frame#93]
I would really like to contribute to this project, but other than TODO-s in the code, there is no way to know about tasks/ideas the community can pick up and experiment with.

Possible entries:
 - Increase code coverage
 - Update to latest core.async once it's released and implement purge-chan
 - etc...

An example: 
https://github.com/jsbin/jsbin/blob/master/docs/roadmap.md

**Comment by danielcompton** [comment]
I hope I'm not speaking out of turn, but I don't think there is a specific roadmap for re-frame beyond any outstanding issues, PR's, or TODO's. Of course @mike-thompson-day8 has his secret plan for world domination where re-frame plays a big part but I'm not allowed to share that one :)
