### ISSUE TITLE
TodoMVC example looks bad on Firefox, Clear Completed button doesn't work

### ISSUE THREAD

**Issue by thenonameguy** [Day8/re-frame#94]
Tested with Firefox 39.0 on OSX 10.9.5

Chrome:
<img width="598" alt="screen shot 2015-07-25 at 3 05 45 pm" src="https://cloud.githubusercontent.com/assets/2217181/8889549/dceed066-32de-11e5-9170-2b6f5b7aa191.png">

Firefox:
<img width="593" alt="screen shot 2015-07-25 at 3 06 32 pm" src="https://cloud.githubusercontent.com/assets/2217181/8889550/e44e6880-32de-11e5-9455-48e8c245c9f3.png">

Clicking Clear Completed doesn't trigger the dispatch, nor does rewriting the `:on-click` to `(js/alert 'test')`. Also rewriting the text from 'Clear completed' to anything doesn't get reloaded with figwheel, but (oddly) every other part of the page gets rewritten correctly/works.

Very odd. Couldn't find a solution. Halp.

**Comment by kamn** [comment]
Looking into it there is a css class that is setting the content to be 'Clear completed'. It completely ignores the cljs view code. I am working on a pull request for fixing it.

**Comment by kamn** [comment]
Also in case anyone else comes along and wonders why Firefox has checkboxes it boils down to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=605985). You can't easily restyle checkboxes like you can in webkit.There are some solutions in the comments if someone wants to try though.

**Comment by thenonameguy** [comment]
Thanks @kamn!

**Comment by mike-thompson-day8** [comment]
When doing todomvc, you have to use the offical CSS file from https://github.com/tastejs

I seem to remember using something like this: 
https://github.com/tastejs/todomvc/blob/master/examples/backbone/node_modules/todomvc-app-css/index.css

Have there been changes to cover the firefox issues?

**Comment by mike-thompson-day8** [comment]
I'm going  to close this issue.  As far as I can tell, we're using a pretty up to date CSS file from the official todomvc site.  If that is wrong, please provide a PR with the correct  CSS.
